### ISSUE TITLE
mqmetric - example needed

### ISSUE THREAD

**Issue by matsta** [ibm-messaging/mq-golang#10]
Hi Mark,

Can you give an example on how to use the metric lib for meassuring the queue depth? You have done a great job here but there is almost no sample code on how to use these libs. I think it will be very benificial for the project and for newcomers to understand how to use it. Don't you agree?

BR
Mathias

**Comment by ibmmqmet** [comment]
Thanks for the comment.

In MQ, there are two ways of getting the current queue depth, both of which can be extrapolated from examples already in the Go source code. Neither do exactly what you want directly, but if you understand the general MQ API or how PCF operations work, then you can use those pieces as starting points.

1. MQINQ: in mqitest.go, there's code showing how MQINQ is called. The particular example code is opening the qmgr object and getting the qmgr name and a couple of other attributes. For qdepth, you would open a queue object and build a suitable selector array.

2. PCF is the more general interface for administration, as MQINQ can only return a small number of attributes for an object. In mqmetric/discover.go there's code showing how to make a PCF query, get a response and parse it. The code here is doing INQUIRE_Q_NAMES, but could just as easily be INQUIRE_Q_STATUS to get the depth.

What I'm hoping is that people can read the MQ documentation, for example on [PCF programming,](http://www.ibm.com/support/knowledgecenter/SSFKSJ_8.0.0/com.ibm.mq.ref.adm.doc/q086860_.htm) and use that general material as the basis of any further PCF operations using the Go interface. The principles don't change, only the detailed spelling for each operation and its parameters.

The mqmetric package is not the right place to add more general admin code; I intended that specifically to work with the published resource statistics. But I might consider adding fragments to another package or perhaps as simple commands (or _test functions) later; and of course there's always the opportunity for other people to contribute examples if they want.
