### ISSUE TITLE
Link fail when i install ibmmq

### ISSUE THREAD

**Issue by d4rk5eed** [ibm-messaging/mq-golang#100]
MQ: mqadv_dev912_ubuntu_x86-64
mq-golang: 1d65851f7c0b8ef6de65e0e2541f350d35fd7e26 , master
go: version go1.7.4 linux/amd64
os: Ubuntu based on 4.14 kernel

➜  echo $GOROOT 
/usr/lib/go
➜  echo $GOPATH
/home/nemoq/gowork
➜  echo $CGO_LDFLAGS_ALLOW
-Wl,-rpath,*
➜ echo $CGO_LDFLAGS      
-L/opt/mqm/lib64 -Wl,-rpath,/opt/mqm/lib64
➜ echo $CGO_CFLAGS 
-I/opt/mqm/inc

When I invoke ➜  gowork go install -v ./src/github.com/ibm-messaging/mq-golang/ibmmq

I receive 
github.com/ibm-messaging/mq-golang/ibmmq
/tmp/go-build234374910/github.com/ibm-messaging/mq-golang/ibmmq/_obj/_cgo_main.o:(.data.rel+0x0): undefined reference to `NULL'
collect2: error: ld returned 1 exit status

**Comment by ibmmqmet** [comment]
I've seen that in older levels of the Go compiler. Don't know why it happens, but current levels don't show that problem. Try moving to at least 1.10 of the Go compiler.

**Comment by d4rk5eed** [comment]
> I've seen that in older levels of the Go compiler. Don't know why it happens, but current levels don't show that problem. Try moving to at least 1.10 of the Go compiler.

yep, it succeeded with 1.11
thanks
