### ISSUE TITLE
Queue max depth

### ISSUE THREAD

**Issue by salapat11** [ibm-messaging/mq-golang#101]
Can max depth or % full of a queue be obtained from the metrics that are being collected?

**Comment by ibmmqmet** [comment]
No. The only value reported from the published statistics or from QSTATUS output is the current qdepth.

**Comment by salapat11** [comment]
Thank you.  We want to leverage Prometheus alerting when queue depth reaches a certain threshold.

**Comment by ibmmqmet** [comment]
[MQ events](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.mon.doc/q036430_.htm) are designed to allow alerting when a queue is getting full. But those have to be handled in a different fashion. It's an MQ message to be interpreted (eg by the amqsevt sample). I would not want to add event processing here as most of the information in events are not really metrics.

You could always try opening an RFE to ask for %full to be added to the published resource stats from the qmgr. But there are no guarantees that would get implemented.
