### ISSUE TITLE
Monitoring on iseries

### ISSUE THREAD

**Issue by salapat11** [ibm-messaging/mq-golang#102]
Can monitoring be extended to iSeries queue managers?  When I tried the current package it fails with this error - "Cannot access queue manager. Error: Queue manager must be at least V9.0 for monitoring."

Would like to have it working like z/OS queue managers with limited metrics.

**Comment by salapat11** [comment]
I tweaked the code to ignore pub/sub for iseries platform (MQPL_OS400) with similar settings as z/OS. And it works.

**Comment by ibmmqmet** [comment]
And which version of MQ is running on that platform? V9 supports essentially the same pub/sub resources as other Distributed platforms

**Comment by salapat11** [comment]
v8

**Comment by salapat11** [comment]
Can the channel, queue metrics be collected via STATUS commands on zlinux v8 servers?  Similar to z/OS and OS400.

**Comment by ibmmqmet** [comment]
Once again, zLinux is another Distrbuted platform and hence has the published resource statistics from V9 onwards. I don't plan to extend the function of these monitors back to the V8 platforms where the publications did not exist but now do.

z/OS is the special case, as it does not have that capability at all and it's no different at V8 or V9.

**Comment by felix-lessoer** [comment]
@salapat11 I implemented a solution to do so also in older versions of IBM MQ on top of this mq-golang project. It is using different Inquire commands directly to achieve sth. similar as with PubSub.
Have a look at https://github.com/felix-lessoer/qbeat if you want to have a look. Not yet tested with iseries but happy to discuss about it.

**Comment by ibmmqmet** [comment]
answered

**Comment by salapat11** [comment]
> @salapat11 I implemented a solution to do so also in older versions of IBM MQ on top of this mq-golang project. It is using different Inquire commands directly to achieve sth. similar as with PubSub.
> Have a look at https://github.com/felix-lessoer/qbeat if you want to have a look. Not yet tested with iseries but happy to discuss about it.

Thanks @felix-lessoer.  Will take a look.
