### ISSUE TITLE
iSeries platform support

### ISSUE THREAD

**Issue by salapat11** [ibm-messaging/mq-golang#104]
Can support to iSeries platform be added similar to z/OS?  The code base worked when it was tweaked to include OS400 platform along with z/OS.  Would like to see the changes here rather than we maintaining a separate code base.

**Comment by ibmmqmet** [comment]
This is not really a request for iSeries support, but for V8 support. I will consider it, but given the limitations of what can be monitored (there's no choice for z/OS), it's much better to move to V9 on all the other platforms.

**Comment by salapat11** [comment]
Thank you.  We have a plan to upgrade to v9 soon.  This will be temporary adjustment until the upgrade.

**Comment by ibmmqmet** [comment]
Enabled in V4.0.6 but still not recommended

**Comment by salapat11** [comment]
Thank you.
