### ISSUE TITLE
Queue Max Depth Percent Metric

### ISSUE THREAD

**Issue by Forrin** [ibm-messaging/mq-golang#105]
An important metric that our team needs to know is the queue depth percent (how full a queue is). Currently the depth is exposed as a metric using the Q Status command. What I propose is leveraging the Inquire Q command to get the max depth. Then with these two pieces of data the percent full metric can be determined. It's just a little bit of math that could be done in either the exporter or the mqmetric library.

Here is a link to the documentation on the inquire queue command:  https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.ref.adm.doc/q087800_.htm

Thanks

**Comment by Forrin** [comment]
@ibmmqmet Any comments on this request?

**Comment by ibmmqmet** [comment]
See V4.0.6
