### ISSUE TITLE
3 variables but qMgrObject.Inq returns 2 values

### ISSUE THREAD

**Issue by garrotemar** [ibm-messaging/mq-golang#107]
I'm following the procedure to install ibm-messagin/mq-golang
When run this:
# go build -o bin/mqitest ./src/github.com/ibm-messaging/mq-golang/samples/mqitest/*.go

Obtain the following error:
command-line-arguments
src/github.com/ibm-messaging/mq-golang/samples/mqitest/mqitest.go:250:28: assignment mismatch: 3 variables but qMgrObject.Inq returns 2 values
src/github.com/ibm-messaging/mq-golang/samples/mqitest/mqitest.go:250:45: too many arguments in call to qMgrObject.Inq
        have ([]int32, number, number)
        want ([]int32)

Operating System: RedHat 7
MQ ( IBM_MQ_9.0.0.0_LINUX_X86-64Client )
mq-golang ( latest )
Go compiler ( go1.12.5 )

**Comment by ibmmqmet** [comment]
V4.0.6 includes a solution for this
