### ISSUE TITLE
Connection to SSL channels

### ISSUE THREAD

**Issue by salapat11** [ibm-messaging/mq-golang#109]
Hi Mark,

I'm trying to use the exporter in client mode and connect to a SSL channel.

export MQSAMP_USER_ID=xxxx
export MQSERVER='<ssl_channel>/TCP/<server(port)>'

It failed with MQCONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_SSL_INITIALIZATION_ERROR [2393] 

How am I supposed to pass the keystore?

**Comment by ibmmqmet** [comment]
For any connection configuration more complex than the MQSERVER environment variables allows, you need to use a CCDT. That would include TLS attributes for the channel. 

The location of the CCDT file and the keystore will then usually be set by further environment variables (MQCHLLIB, MQCHLTAB, MQSSLKEYR) or in the mqclient.ini file.

**Comment by salapat11** [comment]
Thanks, Mark.
