### ISSUE TITLE
TLS Connection

### ISSUE THREAD

**Issue by jgrusewski** [ibm-messaging/mq-golang#11]
Hi Mark, 

I need to connect to a queue manager using TLS, do you have an example for me how this can be done with this package.

If I look at https://gist.github.com/osanchezhuerta/0055e978221872e262c25e52a0979ca1 
this is configured in MQCD_CLIENT_CONN_DEFAULT. 

Br. Jeroen

**Comment by ibmmqmet** [comment]
I've just pushed a new set of code to the repo including support for the MQCD structure to allow programmatic access for clients. There's also a new sample, clientconn, that shows how to use it. While it doesn't include showing the TLS parameters, they are also available to be set much like the C programs.
