### ISSUE TITLE
Method Get - panic "runtime error: index out of range" if incorrect MsgId

### ISSUE THREAD

**Issue by romapres2010** [ibm-messaging/mq-golang#111]
If I try to call method Get with incorrect MsgId, for example to byte less "414d5120514d3420202020202020202090b7355d218920" instead of 
"414d5120514d3420202020202020202090b7355d21892013"
I received panic "runtime error: index out of range"

- Version MQ - 9.0.0, mq-golang -, Go - 1.12

**Comment by ibmmqmet** [comment]
added some validation for parameters in latest push

**Comment by romapres2010** [comment]
it seems ok
