### ISSUE TITLE
mq_prometheus deployed in openshift

### ISSUE THREAD

**Issue by salapat11** [ibm-messaging/mq-golang#113]
Mark,

I was able to successfully run MQ prometheus in a container deployed in Openshift when exporting the MQSERVER environment variable (simple, non SSL connection).  However when using CCDT and keystore (SSL connection), it fails with the below error.  CCDT and keystore are loaded as volumes.  Any ideas?

Comment1          :- xcsGetpwuid failed to get password entry for process   |
|   with real uid 1002390000.                                                 | 
| Comment2          :- Details: getuid() returned 1002390000;                 |
|   getpwuid_r(1002390000) failed with errno=0.                               | 
| Comment3          :- A user name of "UNKNOWN" will be used, which will      |
|   likely cause later authorisation failures. Note this FFST can be turned   |
|   off by exporting env var AMQ_NOFFST_PROCESS_UID.                          | 

Error: MQCONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_CHANNEL_CONFIG_ERROR [2539]

**Comment by ibmmqmet** [comment]
That message is a warning, not a fatal error. And as it says, it can be suppressed.

Openshift tends to run things with random ids for security reasons, so connecting as a client to a qmgr will require identification to be provided in some other fashion such as a CHLAUTH mapping rule, or userid/password passed on the connection.

Is there anything in the error logs at the client or qmgr end that says more about the 2539

**Comment by salapat11** [comment]
Thanks for the response, Mark.  Here is the qmgr log.  

----- amqrmrsa.c : 938 --------------------------------------------------------
08/12/2019 07:52:35 AM - Process(71398.51) User(mqm) Program(amqrmppa)
                    Host(xxxxx) Installation(Installation1)
                    VRMF(9.0.0.3) QMgr(xxxxx)
                   
AMQ9209: Connection to host 'xxxxx (xx.xx.xx.xxx)' for channel
'PROM_SECCLNT' closed.

EXPLANATION:
An error occurred receiving data from 'xxxxx (xx.xx.xx.xxx)' over
TCP/IP.  The connection to the remote host has unexpectedly terminated. 

The channel name is 'PROM_SECCLNT'; in some cases it cannot be determined and
so is shown as '????'.
ACTION:
Tell the systems administrator.
----- amqccita.c : 4192 -------------------------------------------------------
08/12/2019 07:52:35 AM - Process(71398.51) User(mqm) Program(amqrmppa)
                    Host(xxxxxx) Installation(Installation1)
                    VRMF(9.0.0.3) QMgr(xxxxx)
                   
AMQ9999: Channel 'PROM_SECCLNT' to host 'xx.xx.xx.xxx' ended abnormally.

EXPLANATION:
The channel program running under process ID 71398 for channel 'PROM_SECCLNT'
ended abnormally. The host name is 'xx.xx.xx.xxx'; in some cases the host name
cannot be determined and so is shown as '????'.
ACTION:
Look at previous error messages for the channel program in the error logs to
determine the cause of the failure. Note that this message can be excluded
completely or suppressed by tuning the "ExcludeMessage" or "SuppressMessage"
attributes under the "QMErrorLog" stanza in qm.ini. Further information can be
found in the System Administration Guide.

**Comment by salapat11** [comment]
https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.tro.doc/q045390_.htm - What is the code page that was mentioned in this link?  

I got the CCDT and SSL config working from my local laptop (Mac) but not from docker container (Linux).  Is there a difference in the code page between the two OS?

**Comment by salapat11** [comment]
The issue is resolved.  Apparently, my MQ sdk image is missing gskit8 library and could not process the certs.  I have been using mq-sdk package from mq-container Github.  

What is the best approach to build a client library?  For now, I copied the Dockerfile partially that you used to compile and build the prometheus binary.  

ARG BASE_IMAGE=ubuntu:18.10
FROM $BASE_IMAGE

# Location of the downloadable MQ client package \
ENV RDURL="https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/redist" \
    RDTAR="IBM-MQC-Redist-LinuxX64.tar.gz" \
    VRMF=9.1.0.2

# Install the Go compiler and Git
RUN export DEBIAN_FRONTEND=noninteractive \
  && bash -c 'source /etc/os-release; \
     echo "deb http://archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME} main restricted" > /etc/apt/sources.list; \
     echo "deb http://archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME}-updates main restricted" >> /etc/apt/sources.list; \
     echo "deb http://archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME}-backports main restricted universe" >> /etc/apt/sources.list; \
     echo "deb http://archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME} universe" >> /etc/apt/sources.list; \
     echo "deb http://archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME}-updates universe" >> /etc/apt/sources.list;' \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    tar \
    bash \
    build-essential \
  && rm -rf /var/lib/apt/lists/*

# Create location for the MQ installation
RUN mkdir -p /opt/mqm \
  && chmod a+rx /opt/mqm

# Install the MQ client from the Redistributable package. This also contains the
# header files we need to compile against.
RUN cd /opt/mqm \
 && curl -LO "$RDURL/$VRMF-$RDTAR" \
 && tar -zxf ./*.tar.gz \
 && rm -f ./*.tar.gz

**Comment by ibmmqmet** [comment]
The redist client package that the Dockerfile uses contains everything needed to build and run client programs including the gskit component. That's what I use in my containers. You could separate into build and runtime operations - a runtime-only container might be able to exclude some of the packages (for example gcc wouldn't be needed, and the MQ redist package could be trimmed during the build to just the pieces needed via its genmqpkg command) to be smaller but it probably wouldn't save a huge amount of space.

**Comment by salapat11** [comment]
When I used the redist client package, it failed to run in Openshift.  It ran successfully as a container on my laptop.  It failed with this error in openshift -
AMQ6235E: Directory '' missing.
Segmentation fault

**Comment by ibmmqmet** [comment]
That sounds like something to be investigated by support via a PMR

**Comment by ibmmqmet** [comment]
I just tried running the commands in a local container which did not have the userid fully defined and got that AMQ6235 message - the client code is trying to access directories under the user's home directory which it can't find or create. Try "export HOME=/tmp" to give it a path that exists in the container and which anyone can write to.

**Comment by salapat11** [comment]
Thank you.  I will export the HOME variable and try again.
