### ISSUE TITLE
BROWSE Messages not possible?

### ISSUE THREAD

**Issue by wolf4git** [ibm-messaging/mq-golang#116]
I was looking for BROWSE Messages, but was not able to find samples.
Is it not possible with this repo to do MQGMO_BROWSE_FIRST / MQGMO_BROWSE_NEXT.
If it is possible whould you be so kind and provide an example...
I don't catch what Flags to set on qMgr, qObject and what method to use on qObject to Browse
...THX in advance

**Comment by ibmmqmet** [comment]
There being no specific sample should not stop you using the browse flags. They can be used in exactly the same way as for other languages. See for example https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.dev.doc/q026460_.htm 

The amqsget sample uses the options for destructive get; you ought to be able to see how to change the MQOO and MQGMO flags to do browsing.

**Comment by wolf4git** [comment]
Thanks a lot, so I’ll investigate some effort to get this running
Again..THX

**Comment by wolf4git** [comment]
Ok, BROWSE is working fine, thanks Gin for our Feedback.
Perhaps you can directly give me an answer to my next experience.

Browse,Get,Put works perfect against my docker-mqserver Version 9x.
Testing Browse against our Pre-Production works also, but

Testing Browse against Production fails with Auth-Failure.
My Question: Is this go-code able to connect to older Versions of Mq-Server e.g 7.x ???

**Comment by ibmmqmet** [comment]
It can certainly connect to older versions of MQ. But V7 does not have inbuilt authentication so you may need to modify programs or qmgr configuration depending on what the exact error is. Which will be shown in the qmgr error logs.

**Comment by wolf4git** [comment]
Yeah, you are again right...solved it 
commented "cno.SecurityParms = csp" 
now qMgr, err = ibmmq.Connx(iConfig.ManagerName, cno)...works also on Version 7
THX
