### ISSUE TITLE
IBM MQ Compilation Error

### ISSUE THREAD

**Issue by lukecolpo** [ibm-messaging/mq-golang#119]
Running go1.13 darwin/amd64
GOPATH: /users/lukecolpo/gowork
GOROOT: /usr/local/go

When I run the following command
`go install ./src/github.com/ibm-messaging/mq-golang/ibmmq`

I receive the following error:
'can't load package: package ./src/github.com/ibm-messaging/mq-golang/ibmmq: cannot find package "." in:
	/Users/lukecolpo/gowork/src/github.com/ibm-messaging/mq-golang/src/github.com/ibm-messaging/mq-golang/ibmmq'

**Comment by ibmmqmet** [comment]
I think the command you should use is simply `go install ibmmq` - without the path

**Comment by lukecolpo** [comment]
Thank you Mark!
