### ISSUE TITLE
Using pmo.Context option

### ISSUE THREAD

**Issue by ravellan** [ibm-messaging/mq-golang#122]
Unless I am missing something it is not possible to use the pmo.Context option right now since the C.MQHOBJ field of MQObject is unexported.

The solution I came up with without exporting anything is to add a method to MQPMO like this
```
// SetContext sets the Context option
// to supplied MQObject queue handle
func (pmo *MQPMO) SetContext(o MQObject) {
	pmo.Context = o.hObj
}
````
Thoughts?

**Comment by ibmmqmet** [comment]
Thanks for pointing that out. One of those unimplemented features that I'd never got to because noone was using it! I've just pushed a new version that enables Context to be set in a way that's more like the C mechanism - `pmo.Context = qObject`

**Comment by ravellan** [comment]
Even better solution and it works well. Thanks!
