### ISSUE TITLE
MQRC_ENVIRONMENT_ERROR 

### ISSUE THREAD

**Issue by zyf7862634** [ibm-messaging/mq-golang#124]
Please include the following information in your ticket.

- Version information for MQ, mq-golang, Go compiler
- A small code sample that demonstrates the issue.

run mq by  docker：
docker run  - --env LICENSE=accept   --env MQ_QMGR_NAME=QM1   --publish 1414:1414   --publish 9443:9443 --name mqm --detach  ibmcom/mq:9.1.3.0 

but the result: MQCONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_ENVIRONMENT_ERROR [2012] , when i run cmd  './amqsconn QM1 "DEV.APP.SVRCONN" "127.0.0.2(1414)" '  at my vbox ubuntu16.04

**Comment by ibmmqmet** [comment]
No particular reason comes to mind. That error may come from having multiple copies of the MQ client libraries installed, and confusion over what gets loaded via LD_LIBRARY_PATH settings. But it may need to be investigated via an MQ trace (use strmqtrc/endmqtrc/dspmqtrc).

Also look for any error logs (either under /var/mqm or $HOME/IBM/MQ).

**Comment by zyf7862634** [comment]
> No particular reason comes to mind. That error may come from having multiple copies of the MQ client libraries installed, and confusion over what gets loaded via LD_LIBRARY_PATH settings. But it may need to be investigated via an MQ trace (use strmqtrc/endmqtrc/dspmqtrc).
> 
> Also look for any error logs (either under /var/mqm or $HOME/IBM/MQ).

if don`t install mqclient pkg(deb/rpm) at my ubuntu64, only copy libmqm_r.so and libmqe_r.so,  that go build cmd successful but run my application err: MQRC_ENVIRONMENT_ERROR,  I want ask that i miss some env so get err?

**Comment by ibmmqmet** [comment]
If you've not got all of the libraries, it's not surprising you get an error. Runtime needs more than just the libraries used to compile against.

You need to either use the rpm/deb file for the MQ client, or get the Redist client package unzipped somewhere, similar to how it's done in the Dockerfile in the root of this repo.

**Comment by zyf7862634** [comment]
> If you've not got all of the libraries, it's not surprising you get an error. Runtime needs more than just the libraries used to compile against.
> 
> You need to either use the rpm/deb file for the MQ client, or get the Redist client package unzipped somewhere, similar to how it's done in the Dockerfile in the root of this repo.

thank you !   a moment ago  correct this issue that  i copy ccsid_part2.tbl and ccsid.tbl to /opt/mqm/samp
