### ISSUE TITLE
Performance implications with increasing max handles

### ISSUE THREAD

**Issue by JJinMaine** [ibm-messaging/mq-golang#127]
I've recently learned that I need to consider 4 handles per queue as I'm trying to size out how I would use these tools in a real life environment. I'm trying to understand performance implications if we start increasing max handlers on our real queue managers. If we have 1000 queues on a queue manager, it sounds like we'll need to increase max handles to at least 4K - maybe 5K to cover incidentals. What are the performance implications? How have these monitoring tools been tested at scale? Are there guidelines and best practices for trying to use this with over X hundreds or thousands of queues per queue manager? Thanks!

**Comment by ibmmqmet** [comment]
There's no performance implication simply by increasing maxhandles. That control is intended to stop runaway applications from continuing to open resources without limit. 

I've heard of other people hitting some of these kinds of limits using default qmgr values with the monitoring, so they must be collecting data on a reasonable number of queues or channels. But I don't have specific numbers. 

Main thing is likely to be to only select to monitor objects that are important - ie you'd probably want not to monitor the default SYSTEM queues.
