### ISSUE TITLE
Channel counts

### ISSUE THREAD

**Issue by salapat11** [ibm-messaging/mq-golang#129]
Mark,

Will it be possible to add a metric for channel count for each channel (that counts the channels that are running)?   Currently we measure the count using the count query after the samples are collected.  But it would be more useful if we can have a metric for that.  

Also, a metric for max channel count on a queue manager.

**Comment by ibmmqmet** [comment]
Prometheus is the best way to count metrics. It can do various groupings automatically. 
For example, 
```
count by (channel,qmgr) (ibmmq_channel_status)
```
gives a graph of number of active channels for each qmgr.

I could consider adding MaxChannels for z/OS as it is available via MQINQ. But not for Distributed platforms as the corresponding controls are in the qm.ini file, not readily accessible in a program.

**Comment by salapat11** [comment]
Mark, thanks for the response.  Yes.  I am using the same metric but given the number of samples for some queue managers, it is taking a long time to return the query.
