### ISSUE TITLE
Connecting  to multiple QMGRs

### ISSUE THREAD

**Issue by usuresh80** [ibm-messaging/mq-golang#13]
I would not say this issue , But I need some  usage related information 
https://www.ibm.com/developerworks/community/blogs/messaging/entry/IBM_MQ_Using_Prometheus_and_Grafana_to_montor_queue_managers?lang=en
in  this example  we can connect one queue manager,  But how we can connect to multiple QMGRs  using client connection from a centralized server ?

can I run  below  command  multiple times for  each qmgr ( I am using client connections)  and diffrent Port number and  can I update yaml file with differnet port numbers but same Jobname 
exec /usr/local/bin/mqgo/mq_prometheus -ibmmq.queueManager=$qMgr -ibmmq.monitoredQueues="$queues" -log.level=error

Let me know  if I am not clear

**Comment by usuresh80** [comment]
tried running multiple exec .. statement for different qmgrs in different ports,  code pulling stats and exposing on different  ports but it  prometheus is  pulling information from only one port , 
in below example prometheus is pullling information from only 9158 

- job_name: 'ibmmq'
    scrape_interval: 15s

    static_configs:
       - targets: ['hostname.example.com:9157']

    static_configs:
       - targets: ['hostname.example.com:9158']

**Comment by ibmmqmet** [comment]
I have used this syntax for getting multiple monitors in the same job_name clause

```
 static_configs:
  - targets: ['xxxxx.hursley.ibm.com:9157', 'xxxxx.hursley.ibm.com:9158']
```

It seemed to work.
