### ISSUE TITLE
Unable to statically link the go programs

### ISSUE THREAD

**Issue by abudavis** [ibm-messaging/mq-golang#130]
In order to use the sample program in an environment that does not have MQ libraries installed, I tried to statically link the programs, but while it is able to see the package "ibmmq", it seems as if it is unable to load the package, please see the command used and the error below:

MQ is installed on Ubuntu on default location /opt/mqm
GOPATH=/var/mqm/go
Version information for MQ 9.1.3, mq-golang v1.13.4
This is now tested on Ubuntu X86 VM and on a Mac with same results.

# env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -v -o /var/mqm/go/bin/amqsconnx64 ./src/github.com/ibm-messaging/mq-golang/samples/amqsconn.go
unicode/utf8
runtime/internal/sys
internal/race
math/bits
runtime/internal/atomic
internal/cpu
unicode
sync/atomic
runtime/internal/math
internal/testlog
internal/bytealg
math
runtime
internal/reflectlite
sync
errors
sort
internal/oserror
io
strconv
syscall
bytes
strings
bufio
reflect
internal/syscall/unix
time
internal/poll
internal/fmtsort
encoding/binary
os
fmt
encoding/hex
github.com/ibm-messaging/mq-golang/ibmmq
command-line-arguments
# command-line-arguments
src/github.com/ibm-messaging/mq-golang/samples/amqsconn.go:52:11: undefined: ibmmq.MQQueueManager
src/github.com/ibm-messaging/mq-golang/samples/amqsconn.go:68:9: undefined: ibmmq.NewMQCNO
src/github.com/ibm-messaging/mq-golang/samples/amqsconn.go:69:8: undefined: ibmmq.NewMQCD
src/github.com/ibm-messaging/mq-golang/samples/amqsconn.go:90:10: undefined: ibmmq.NewMQCSP
src/github.com/ibm-messaging/mq-golang/samples/amqsconn.go:105:14: undefined: ibmmq.Connx
src/github.com/ibm-messaging/mq-golang/samples/amqsconn.go:115:18: undefined: ibmmq.MQReturn

**Comment by ibmmqmet** [comment]
The MQ runtime libraries (libmqm etc) are only avaliable as shared libraries. They must be available both for compile and runtime. See the build*.sh and Dockerfile in the root of this repo for how to easily download and use that runtime.

**Comment by ibmmqmet** [comment]
Closing as dup of #120
