### ISSUE TITLE
Queue manager memory

### ISSUE THREAD

**Issue by salapat11** [ibm-messaging/mq-golang#131]
Mark,

What does this metric represent - ibmmq_qmgr_ram_total_estimate_for_queue_manager_bytes?

ibmmq_qmgr_ram_total_bytes - This shows the total memory on the server where queue manager resides.

**Comment by ibmmqmet** [comment]
ram_total_bytes is what the qmgr thinks is available as real memory in the box (eg 32GB)
Command line to see it is `amqsrua -m QM1 -c CPU -t SystemSummary`
If you have multiple qmgrs on the box, they should all be reporting the same number.

qmgr_ram_total_estimate is the amount of (probably virtual) memory that we think is in use by the qmgr processes. This one is very very approximate. but we've sometimes used it to detect memory leakage before going into deeper debug. Commaned line to see this one is `amqsrua -m QM1 -c CPU -t QMgrSummary`. The long description on that output is what is converted into the metric name for Prometheus.

**Comment by salapat11** [comment]
I was using qmgr_ram_total_estimate to determine the memory used by the queue manager.  But this number kept on increasing and reached to 80% of the total memory which indicates there is a problem.  But the ibmmq_qmgr_ram_free_percentage shows 50% is free.  But as you mentioned, it is very very approximate.
