### ISSUE TITLE
Exclude some queues using patterns

### ISSUE THREAD

**Issue by piotrekbed** [ibm-messaging/mq-golang#132]
Is  any chance to  exclude queues from monitoring using -ibmmq.monitoredQueues. 
e.g.:
I want to monitoring all queues starting from letter A  -ibmmq.monitoredQueues="A*" exclude AZ*.

Regards
Piotrek

**Comment by ibmmqmet** [comment]
`monitoredQueues="A*,!AZ*"`

**Comment by piotrekbed** [comment]
It's works! thank you.
