### ISSUE TITLE
Queue pattern

### ISSUE THREAD

**Issue by salapat11** [ibm-messaging/mq-golang#133]
We have a queue pattern that resolves to ~750 queues.  If this pattern is used, we noticed it fails with the error - "mqiPCF.go: Unknown PCF type".  When the queue pattern is split into smaller groups, it works.  Is this because of the bufSize assigned as here? - https://github.com/ibm-messaging/mq-golang/blob/bf7e7cff9e763e5dac432590cf4964b44089ff18/mqmetric/discover.go#L714

**Comment by ibmmqmet** [comment]
Not likely to be that - as the code/comments around that area say, the buffer is resized dynamically with retries. I've tried running with 1000 queues in the same pattern and it seems to work fine. (And I can see that buffer being resized.) I'll see if I can add some debug for the next iteration, to get a better idea of what might be happening.

**Comment by rjseibert** [comment]
I would suggest that #163 resolves this.
