### ISSUE TITLE
Future of mq-golang

### ISSUE THREAD

**Issue by ColinSullivan1** [ibm-messaging/mq-golang#134]
First, thank you for all the work and contributing this to the open-source community!

Given the health warning in the README, what is the future of this package?

I can see there's been ongoing development over the last four years, quite a few releases, the project seems stable and healthy, issues are being resolved, and other packages have been build atop of this, e.g. [mq-golang-jms20](https://github.com/ibm-messaging/mq-golang-jms20) (which does not have the health warning).  It'd be great if you could consider this package for official IBM support.

Is there a statement you can give on the viability and future of this project so we can plan accordingly?  Or would there be an alternate golang package that is (or will be) officially supported?

Thanks!

**Comment by ibmmqmet** [comment]
There are no current plans for any "official" support in the sense of being able to open PMRs/Cases against this code. But it is fairly well embedded into the internal development ecosystem, with updates alongside new releases of the underlying MQ interfaces etc. And if use of this package exposes problems in the underlying MQ client code, then you can get official support for anything in that layer as long as you are running supported versions of the qmgr. 

I do have plans for continued enhancements as necessary. There'll be a release with a new major number at some point (a couple of things I want to do will need that to happen) and that'll be the time to remove the health warning. Or at least tone it down.

**Comment by ColinSullivan1** [comment]
@ibmmqmet , Thank you the update - appreciate it.
