### ISSUE TITLE
How to Rollback a Read-Message

### ISSUE THREAD

**Issue by wolf4git** [ibm-messaging/mq-golang#135]
Dear all, I'm using your code and it's working like a charm.
Never the less i am struggling…
My process is: 
  ReadOneMessage() from Queue, PersistOneMessage(), ...again
But if PersistOneMessage() is failing, I have to Rollback the read Message.

Unfortunately i found nothing for Rollback?

I found Close(goCloseOptions int32),but do not catch how to use this.
I found Begin(gobo *MQBO) / Cmit() / Back(), but again..when and how to use it?

Can you provide any hint for Rollback/Un-Consume the last consumed-massage?

THX

**Comment by ibmmqmet** [comment]
Rollback is done by the MQBACK verb. Which in this package's mapping of names is the Back() function. See under https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.dev.doc/q026790_.htm for more details.

But basically, set the MQPMO_SYNCPOINT/MQGMO_SYNGPOINT flags on Get and Put, then you can use Cmit or Back to manage the outcome of the transaction. 

Begin() is only needed if you are using two-phase transactions with another external participant and with MQ as the XA coordinator.

**Comment by wolf4git** [comment]
Thanks, i'll try and reply to this issue

**Comment by wolf4git** [comment]
It took some time, but THX again it is working...
