### ISSUE TITLE
Read 1 Queue from 2 Processes

### ISSUE THREAD

**Issue by wolf4git** [ibm-messaging/mq-golang#136]
THX a lot for your support so far. 
One additional thing i like to know is,
if i like to read one queue from 2 parallel running progs, how can i do this?
Currently i get "QUEUE alread in use"

**Comment by ibmmqmet** [comment]
MQRC_OBJECT_IN_USE is described in the documentation: https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.tro.doc/q041130_.htm

You need to look at the SHARE/NOSHARE and DEFSOPT attribute on the queue, also possibly the MQOO_INPUT_* value that might have been set in the getting application (the amqsget sample in this repo explicitly asks for exclusive access to the queue).

**Comment by wolf4git** [comment]
I'll try MQOO_INPUT_SHARED at first, as i found this in your repo 
I'll come back tomorrow ;-)

**Comment by wolf4git** [comment]
sorry for the late response, but i solved it, but going to mq-docs and understanding how it works.
Never the less...THX again
