### ISSUE TITLE
Channel data and header compression availability in Golang API

### ISSUE THREAD

**Issue by llorephie** [ibm-messaging/mq-golang#137]
https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_7.5.0/com.ibm.mq.ref.con.doc/q081840_.htm

Are there any plans for support channel data and message compression? Currently all MQCD related fields set to NOT_AVAILABLE: https://github.com/ibm-messaging/mq-golang/blob/master/ibmmq/mqiMQCD.go

**Comment by ibmmqmet** [comment]
I'll probably add it to the next update of the package. It wasn't something that had been asked for before.

**Comment by llorephie** [comment]
Thanks in advance!
