### ISSUE TITLE
Semantic versioning to support go modules

### ISSUE THREAD

**Issue by luedigernet** [ibm-messaging/mq-golang#138]
MQ: 9.1.4 
mq-golang: v4.1.3
go: 13+

Please switch the go.mod file so that it is compatible with the go versioning of modules.
If the repository has the version v4.1.3 it is required that the modulepath in go.mod must end with /v4

**Comment by ibmmqmet** [comment]
Moving to go module versioning requires moving a package to a new major version (once, like this one, it gets past v1). Do it mid-stream introduces incompatibilities for current users. 

Going to a new major version (eg v5) is something I expect to do, but not immediately. My plan is to do it to match up with the next LTS release of IBM MQ. Which has not yet been announced so I can't give any dates.

**Comment by luedigernet** [comment]
I don't  see the breaking change so far. The only thing that is needed is to  fix the go.mod file.
With the existence of the go mod file go 1.13+ requires that version greater then 1 must have  the major version as suffix in the import path. From my understanding that would only fix it for these gophers that are already using go modules. For the older ones which are using dep or glide the go.mod file would be ignored.

**Comment by ibmmqmet** [comment]
See https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

> if you are adopting modules for the first time for a pre-existing repository or set of packages that have already been tagged v2.0.0 or higher before adopting modules, then the recommended best practice is to increment the major version 

Any existing code that is not module-aware but using this code would need changing to pick up new paths. That's the kind of change that requires new major numbers.

**Comment by ibmmqmet** [comment]
v5.0.0 was release this week as a module
