### ISSUE TITLE
src/ibmmq/mqistr.go:25:21: error: cmqstrc.h: No such file or directory

### ISSUE THREAD

**Issue by shanusalunke** [ibm-messaging/mq-golang#14]
I'm running this against IBM Websphere 8.0.1. 

While trying to install mq_coll, I get the following error.

[root@sl73amsapd038 go]# go install ./src/mq_coll
ibmmq
src/ibmmq/mqistr.go:25:21: error: cmqstrc.h: No such file or directory

Looks like cmqstrc.h is supposed to be included in Websphere 8.0.0 but doesn't exist on my server (find returns nothing). 

Do you know where this header should be ? How do I get it if it wasn't included as a part of the installation ?

**Comment by ibmmqmet** [comment]
cmqstrc.h was included in MQ 8.0.0.4

**Comment by shanusalunke** [comment]
What is the minimum or recommended version of MQ to install these plugins against ?

**Comment by ibmmqmet** [comment]
8004 is the absolute minimum to be able to compile the code as I indicated above. 

The monitoring statistics that the various collectors process are only generated from V9.
