### ISSUE TITLE
Security permissions

### ISSUE THREAD

**Issue by njchaltry** [ibm-messaging/mq-golang#145]
What type of security permissions to RACF profiles would be required to run the metric programs against z/OS queue managers?

**Comment by ibmmqmet** [comment]
Essentially you need to be able to put a message to SYSTEM.COMMAND.INPUT and open a model queue to get replies from. And be able to issue various DISPLAY xxSTATUS commands (controlled by the MQCMDS resource profiles, with READ authority needed. See the [KnowledgeCentre](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.sec.doc/q011730_.htm) for command security profiles.
