### ISSUE TITLE
What are the minimum dependencies from MQ ToolKit I need to run this package?

### ISSUE THREAD

**Issue by Must4che** [ibm-messaging/mq-golang#147]
Sorry for asking question like this here. I'm trying to create as light as possible docker container. I followed your Docker example and I was able to cut it down to point that I need to cut out some things from MQ toolkit.

I'm using 9.2.0.0-IBM-MQ-Toolkit and I noticed that in **bin** folder it has **genmqpkg.sh** which serves as an installer(or just gives you chance to choose which dependencies to install).

Which are the bare minimum I need from these?

- 32-bit application support
- support for languages other than English
- C++ libraries
- COBOL libraries
- .NET libraries
- SSL/TLS support
- AMS support
- CICS support
- any administration tools
- any RAS tools
- any sample applications
- the SDK to compile applications
- unthreaded application support

**Comment by ibmmqmet** [comment]
For building code you need the SDK. For runtime, you may need the TLS support depending on how you connect to the qmgr. You may want the non-English support. 

You don't need any of the other subset options. Removing files from within the container may or may not save space in the end, of course, depending on how you build it.

**Comment by ibmmqmet** [comment]
Now that genqkpkg supports removal in-place instead of creating a new tar file, I've removed many of the optional components as part of the Dockerfile builds.
