### ISSUE TITLE
type *C.struct_tagMQCNO has no field or method CCDTUrlOffset

### ISSUE THREAD

**Issue by shanusalunke** [ibm-messaging/mq-golang#15]
compiling against MQv8.0.0.6, see the following when trying to install the plugin

> go install ./src/mq_coll

    # ibmmq
    src/ibmmq/mqiMQCNO.go:153: mqcno.CCDTUrlOffset undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlOffset)
    src/ibmmq/mqiMQCNO.go:155: mqcno.CCDTUrlPtr undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlPtr)
    src/ibmmq/mqiMQCNO.go:156: mqcno.CCDTUrlLength undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlLength)
    src/ibmmq/mqiMQCNO.go:158: mqcno.CCDTUrlPtr undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlPtr)
    src/ibmmq/mqiMQCNO.go:159: mqcno.CCDTUrlLength undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlLength)
    src/ibmmq/mqiMQCNO.go:186: mqcno.CCDTUrlPtr undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlPtr)
    src/ibmmq/mqiMQCNO.go:187: mqcno.CCDTUrlPtr undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlPtr)

Struct defined in src/ibmmq/mqiMQCNO.go with type string. Not familiar with golang but perhaps the type shouldn't be string ? 

    type MQCNO struct {
	Version       int32
	Options       int32
	SecurityParms *MQCSP
	CCDTUrl       string
	ClientConn    *MQCD
	SSLConfig     *MQSCO
    }

Used @153:

    mqcno.CCDTUrlOffset = 0

**Comment by ibmmqmet** [comment]
See https://github.com/ibm-messaging/mq-golang/issues/4
