### ISSUE TITLE
[Feature request] Add abilty to parse RFH2 headers

### ISSUE THREAD

**Issue by llorephie** [ibm-messaging/mq-golang#150]
Any plans to implement other formats for MQMD parser?

https://github.com/ibm-messaging/mq-golang/blob/a7f5d93c3a868dd229d0c847867fc8a25c56e13f/ibmmq/mqi.go#L1363

**Comment by ibmmqmet** [comment]
No current plans. The DLH seemed to be the most likely to be used. It's easier to use message properties than to use the RFH2. And noone's asked for specific additional structures.

**Comment by ibmmqmet** [comment]
closing as answered
