### ISSUE TITLE
Very slow getting message properties

### ISSUE THREAD

**Issue by Ivansamara109** [ibm-messaging/mq-golang#151]
Hello!
When I try to get message properties via 
https://github.com/ibm-messaging/mq-golang/blob/c52ecc2985d7d665677978e52cc6ee026e917e46/samples/amqsprop.go#L168
it takes a very long time to calculate. 

It happens when I receive messages from one destination in different threads within the same ibmmq.MQQueueManager. 
I have tried to :
-  create ibmmq.MQObject by `QMgr.Open(mqod, openOptions)` with a new ibmmq.MQMessageHandle for each thread
-  create one ibmmq.MQObject for all threads with a new ibmmq.MQMessageHandle for each thread
-  create one ibmmq.MQObject with one ibmmq.MQMessageHandle  for all threads

Time increases with the number of threads.
Problem doesn't appear when count of threads is one. 

I'm using github.com/ibm-messaging/mq-golang/v5 v5.1.2
Maybe there is a correct way to create objects in a multi-threaded environment?

**Comment by ibmmqmet** [comment]
In general, only one operation can be done for a given hConn at a time. So it's possible that multiple threads are being serialised behind a lock. The only way to avoid that is to make multiple connections to the qmgr (eg one per thread).
