### ISSUE TITLE
Disabling .FDC and .LOG logging

### ISSUE THREAD

**Issue by Ivansamara109** [ibm-messaging/mq-golang#156]
Hello!

Can I disabling logging on my docker container In /IBM/MQ/data/errors/AMQ*.FDC and AMQ*.LOG files?
Or to limit it's size?

 Thanks!

**Comment by ibmmqmet** [comment]
The [DiagnosticSystemMessages stanza(https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.2.0/com.ibm.mq.con.doc/q130440_.html) in an mqclient.ini file can be used for some control of what goes into error logs. And an MQMAXERRORLOGSIZE  environment variable may also help. 

But if you are getting lots of FDCs, then the solution is to fix whatever is causing them, as FDCs are usually indicative of critical (possibly internal) errors. You can't disable FDCs for that reason.

**Comment by Ivansamara109** [comment]
thanks for the answer!
