### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by hmgo20** [ibm-messaging/mq-golang#157]
We noticed that one of our processes consumed a significant amount of memory. As the main difference to the other processes was the fact that it used MQ (and thus cgo) we created a small program that contains a stripped down version of what we are doing with mq ([worker.zip](https://github.com/ibm-messaging/mq-golang/files/5749878/worker.zip)) (run with: `worker -b=500 -iq=TEST.IN -oq=TEST.OUT -qm=TQM1`).
To create test messages we used [loader.zip](https://github.com/ibm-messaging/mq-golang/files/5749891/loader.zip). Tests were executed with 200,000 msgs (run with: `loader -c 200000 -q TEST.IN -qm TQM1`) . Queue manager resided on a dedicated server, client connection was not encrypted.

Both programs were built using `go build` without any additonal parameters or flags.

Tests were run on a CentOS vm.
```
[go1@vm worker]$ cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
```
```
[go1@vm ~]$ go version
go version go1.15.5 linux/amd64
```
```
[go1@vm worker]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
[go1@vm ~]$ dspmqver
Name:        IBM MQ
Version:     9.2.0.0
Level:       p920-L200709
BuildType:   IKAP - (Production)
Platform:    IBM MQ for Linux (x86-64 platform)
Mode:        64-bit
O/S:         Linux 3.10.0-1160.6.1.el7.x86_64
O/S Details: CentOS Linux 7 (Core)
InstName:    Installation1
InstDesc:
Primary:     Yes
InstPath:    /opt/mqm
DataPath:    /var/mqm
MaxCmdLevel: 920
LicenseType: Production
```

Installed the latest `mq-golang` package (our project is not using go modules, yet).
`[go1@vm worker]$ go get github.com/ibm-messaging/mq-golang/ibmmq`

First we used `top` to investigate RAM consumption. Directly after start the values displayed as follows:
```
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 9145 go1       20   0 1187612  13224   7048 S   0.0  0.3   0:00.02 worker
```
and stayed at this level until test messages were put to the input queue. Then a step by step increase in memory consumption (both VIRT and RES) could be observed until all messages where processed (memory allocation did not get reduced):
```
9145 go1       20   0 2228896 960940   7700 S   0.0 23.8   3:03.60 worker
```
Full data [top.zip](https://github.com/ibm-messaging/mq-golang/files/5749914/top.zip), samples where taken at 30 sec interval.

Setting `GODEBUG=madvdontneed=1` (run with: `GODEBUG=madvdontneed=1 worker -b=500 -iq=TEST.IN -oq=TEST.OUT -qm=TQM1`) did not change the behaviour.

We tried `pprof` (`curl -s http://localhost:6060/debug/pprof/heap > heap_1.out`), but this did not seem to produce usable data.
```
[go1@vm pprof]$ go tool pprof heap_1.out
File: worker
Build ID: 2eced69166c15a9fd765200f511f093c11c44294
Type: inuse_space
Time: Dec 28, 2020 at 1:10pm (CET)
No samples were found with the default sample value type.
Try "sample_index" command to analyze different sample values.
Entering interactive mode (type "help" for commands, "o" for options)
(pprof)
```
Included results ([pprof.zip](https://github.com/ibm-messaging/mq-golang/files/5749951/pprof.zip)) anyway; samples where taken at 30 sec interval.

Running `valgrind` (`valgrind --log-file=/home/go1/result/valgrind/valgrind_extended.log --leak-check=full --show-leak-kinds=all /home/go1/bin/worker -b=500 -iq=TEST.IN -oq=TEST.OUT -qm=TQM1` produced [valgrind.zip](https://github.com/ibm-messaging/mq-golang/files/5749936/valgrind.zip).

At a first glance this looks similar to #99. Could someone please have a look and advise?

**Comment by Ivansamara109** [comment]
Hi.
I met a memory leak in my application when I used messageHandle
If u create messageHandle by qm.CrtMH(cmho), you should to delete it via putHandle.DltMH(ibmmq.NewMQDMHO())

Samples in this project don't do it.

**Comment by hmgo20** [comment]
@Ivansamara109 
Hi,
thanks a lot for the hint! 
In the demo program I added as you suggested:

```
(...)
                err = putHandle.DltMH(ibmmq.NewMQDMHO())
                if err != nil {
                        fmt.Println(err.Error())
                        break
                }
(...)
```
Even when processing 500,000 msgs, memory usage stayed low.

**Comment by Ivansamara109** [comment]
so the problem is resolved?

**Comment by hmgo20** [comment]
Yes, the problem is resolved. 
Many thanks again for the quick help.
Closing this issue now.
