### ISSUE TITLE
CodedCharSetId != 1208

### ISSUE THREAD

**Issue by Ivansamara109** [ibm-messaging/mq-golang#160]
Hello.

When I Get a message with CodedCharSetId != 1208, I need to convert byte body with nonUTF8 symbols to UTF8 string using

```
bodyBuilder := strings.Builder{}
for _, b := range buffer {
	bodyBuilder.WriteString(string(charmap.ISO8859_5.DecodeByte(b)))
}
strContent := strings.TrimSpace(bodyBuilder.String())
msgBodyStr = &strContent
```
or
```
e, _ := charset.Lookup("ISO-8859-5")
r := transform.NewReader(strings.NewReader(*msgStr), e.NewDecoder())
s, _ := ioutil.ReadAll(r)
body:= string(s)
```

maybe I can do Get and receive byte slice with UTF8 content?

**Comment by ibmmqmet** [comment]
MQ will return the data as bytes in the codepage you have requested, provided you've set the MQGMO_CONVERT option and the original message is in a compatible convertible codepage and it's a convertible Format such as MQSTR.
