### ISSUE TITLE
Establish TLS connection from Golang to MQ

### ISSUE THREAD

**Issue by 344271** [ibm-messaging/mq-golang#162]
Please include the following information in your ticket.

- Version information for MQ, mq-golang, Go compiler
- A small code sample that demonstrates the issue.

Hello There,

I need your assistance in connecting to MQ using a secure TLS connection. We are passing the following parameters before calling the MQ connection.

MQ.name 
MQ.user 
MQ.MngrName 
MQ.channel 
MQ.host 
MQ.cipher=TLS_RSA_WITH_AES_128_CBC_SHA256

And we are added the ciphersuites to the channels. 

After passing the above parameters also we are not able to connect to MQ. Could you please assist what I am missing here.
This issue is critical, need your assistance at the earliest. Thank you

**Comment by ibmmqmet** [comment]
Perhaps someone might be able to help if there were a full problem description. What does "not able to connect" actually mean? What error codes are there? What's in the client and server error logs?

**Comment by ibmmqmet** [comment]
Closing as no further update. I guess it wasn't that critical after all.
