### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by 2020testuser** [ibm-messaging/mq-golang#168]
Could anyone please help me? I tried with different version of MQ Client package and no luck.
Thanks in advance!

I'm getting the below error during build.
`# github.com/ibm-messaging/mq-golang/v5/ibmmq
/go/pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.3/ibmmq/mqi.go:54:18: fatal error: cmqc.h: No such file or directory
 #include <cmqc.h>`

Below is my Dockerfile.
`FROM golang:stretch
RUN apt-get update && \
    apt-get install -y curl && \
    curl https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/redist/9.1.5.0-IBM-MQC-Redist-LinuxX64.tar.gz -o mq.tar.gz    && \
    mkdir -p /opt/mqm  && chmod a+rx /opt/mqm && cd /opt/mqm \
    tar -C /opt/mqm -xzf mq.tar.gz
RUN export GOPATH=/Users/testuser/Documents/mq1/mq-source
RUN export PATH=$PATH:$GOPATH/bin
ENV MQ_INSTALLATION_PATH="/opt/mqm"
ENV CGO_LDFLAGS_ALLOW="-Wl,-rpath.*"
ENV CGO_LDFLAGS="-L$MQ_INSTALLATION_PATH/lib64 -Wl,-rpath,$MQ_INSTALLATION_PATH/lib64"
ENV CGO_CFLAGS="-I$MQ_INSTALLATION_PATH/inc"
RUN echo $GOPATH
RUN mkdir -p $GOPATH/src/github.com/triggermesh/mq
WORKDIR $GOPATH/src/github.com/triggermesh/mq
COPY . .
RUN go get
RUN go build -o mq
FROM debian:stretch-slim
WORKDIR /opt/mqm/
COPY --from=0 /opt/mqm .
COPY --from=0 /go/src/github.com/triggermesh/mq/mq .

ENTRYPOINT ["./mq"]
`

**Comment by ibmmqmet** [comment]
you've probably got something wrong with environment variable expansion on the CGO_CFLAGS. Though you shouldn't really need to be setting those as the default will look in /opt/mqm/inc anyway. Using "-x -a" on the go build will show what's really being executed.

**Comment by 2020testuser** [comment]
@ibmmqmet - Thanks Much!
I now get the below error.
`

go: downloading github.com/caarlos0/env v3.5.0+incompatible
go: downloading github.com/ibm-messaging/mq-golang v3.0.0+incompatible
go: downloading github.com/cloudevents/sdk-go v0.11.0
go: downloading knative.dev/eventing-contrib v0.8.2
go: downloading github.com/pkg/errors v0.9.1
go: downloading go.opencensus.io v0.22.2
go: downloading go.uber.org/zap v1.13.0
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
go: downloading go.uber.org/multierr v1.4.0
go: downloading golang.org/x/lint v0.0.0-20191125180803-fdd1cda4f05f
go: downloading go.uber.org/atomic v1.5.1
go: downloading honnef.co/go/tools v0.0.1-2019.2.3
go: downloading go.uber.org/tools v0.0.0-20190618225709-2cfd321de3ee
go: downloading golang.org/x/tools v0.0.0-20200121042740-dbc83e6dc05e
go: downloading github.com/BurntSushi/toml v0.3.1
go: downloading github.com/ibm-messaging/mq-golang v1.0.0
go: downloading github.com/cloudevents/sdk-go v1.2.0
# github.optum.com/Optum-Serverless/mq-source
./main.go:128:23: qObject.GetSlice undefined (type ibmmq.MQObject has no field or method GetSlice)
`
Looks like the version - github.com/ibm-messaging/mq-golang v1.0.0, doesn't contain the method GetSlice. 
Could you please confirm? Also, could you please let me know how I can resolve this issue? Thanks in advance!

**Comment by 2020testuser** [comment]
@ibmmqmet - I got it working! Thanks for your help!

**Comment by frankely** [comment]
> @ibmmqmet - I got it working! Thanks for your help!

How did you fix this issue?
