### ISSUE TITLE
compiling mq-golang fails - cqmc.h not found

### ISSUE THREAD

**Issue by anolting** [ibm-messaging/mq-golang#172]
Hi

I'm trying to compile mq-golang v5.2 on a build machine with RHEL 7.9.

Installed is 
go -> v.1.15
go-toolset -> v1.15
gcc -> 4.8.5-44.el7
git.x86_64 -> 1.8.3.1-23.el7_8 
9.1.0.8-IBM-MQC-Redist-LinuxX64.tar.gz
mq-golang-5.2.0.tar.gz

The machine has no connection to internet therefore git is installed only for internal purposes.

I followed the instructions found on https://github.com/ibm-messaging/mq-golang. As this is a build machine with no MQ installed, the MQC-Redist client is used instead and unpacked to /home/buildusr/mq_client.
The mq-golang packages is unpacked to /git/go/src/github.com/ibm-messaging/mq-golang/

My environment looks like this:

```
export GOROOT=/usr/lib/golang
export GOPATH="/home/buildusr/git/go"
export MQ_INSTALLATION_PATH="/home/buildusr/mq_client"
export CGO_CFLAGS="-I$MQ_INSTALLATION_PATH/inc"
export CGO_LDFLAGS="-L$MQ_INSTALLATION_PATH/lib64 -Wl,-rpath,$MQ_INSTALLATION_PATH/lib64"
export CGO_LDFLAGS_ALLOW="-Wl,-rpath.*"
```

`go install -x -a ./src/github.com/ibm-messaging/mq-golang/ibmmq > compile.log 2>&1`

The compile.log shows the following:

```
CGO_LDFLAGS='"-L/home/buildusr/mq_client/lib64" "-Wl,-rpath,/home/buildusr/mq_client/lib64" "-L/opt/mqm/lib64" "-lmqm_r" "-Wl,-rpath,/opt/mqm/lib64" "-Wl,-rpath,/usr/lib64"' /usr/lib/golang/pkg/tool/linux_amd64/cgo -objdir $WORK/b001/ -importpath github.com/ibm-messaging/mq-golang/ibmmq -- -I $WORK/b001/ -I/home/buildusr/mq_client/inc -I/opt/mqm/inc -D_REENTRANT ./mqi.go ./mqiBO.go ./mqiCBC.go ./mqiCBD.go ./mqiCTLO.go ./mqiDLH.go ./mqiMHO.go ./mqiMPO.go ./mqiMQCD.go ./mqiMQCNO.go ./mqiMQGMO.go ./mqiMQMD.go ./mqiMQOD.go ./mqiMQPMO.go ./mqiMQSCO.go ./mqiMQSD.go ./mqiPCF.go ./mqiSRO.go ./mqiSTS.go ./mqiattrs.go ./mqicb.go ./mqicb_c.go ./mqistr.go
# github.com/ibm-messaging/mq-golang/ibmmq
src/github.com/ibm-messaging/mq-golang/ibmmq/mqi.go:54:18: fatal error: cmqc.h: No such file or directory
 #include <cmqc.h>
                  ^
compilation terminated.
```

I noticed that the value from CGO_CFLAGS is found in the flag CGO_LDFLAGS in compile.log (see line above) but it doesn't seem to be taken by the compiler and I spend several hours searching various sources to figure out why this variable is not respected..

Does someone has ideas?

Best Alex

**Comment by ibmmqmet** [comment]
If I run
```
CGO_CFLAGS=/tmp/mqcc/inc go run -x a amqsput.go
```
from the samples directory I can see lines like
```' 
gcc -I /go/src/github.com/ibm-messaging/mq-golang/ibmmq -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b034=/tmp/go-build -gno-record-gcc-switches -I ./ -I /tmp/mqmcc/inc -I/opt/mqm/inc -D_REENTRANT -o ./_x024.o -c mqistr.cgo2.c
```
in the output. You can see the CGO_CFLAGS has been added to the default options.

Your problem is most likely to do with trying to `install` a package rather than building a runnable program - another one of the effects of the move to modules - different levels of Go compiler have seemed to behave differently with what could be done and their use of GOROOT/GOPATH. Now that it finally seems to have stabilised I ought to go back to the README and delete unnecessary steps.
