### ISSUE TITLE
Question: is there support for ibm Advanced Message Security

### ISSUE THREAD

**Issue by semenovem** [ibm-messaging/mq-golang#173]
Hi Mark!
thanks for supporting and developing this project!

I have a question: 
is it possible to work with "IBM Advanced Message Security" ?

as written about Java
https://www.ibm.com/docs/en/ibm-mq/9.2?topic=scenarios-quick-start-guide-ams-java-clients

Thanks!

**Comment by ibmmqmet** [comment]
This package is built on top of the MQ C client API and libraries so automatically inherits all its support for AMS - specifically it'll be usually using the CMS section (referring to a kdb keystore) of the keystore.conf file.

**Comment by semenovem** [comment]
that's good news, thanks!
