### ISSUE TITLE
Runs on Apple Silicon? (arm64 M1)

### ISSUE THREAD

**Issue by irl-segfault** [ibm-messaging/mq-golang#174]
Does this have any known compatibility issues with the new Apple M1 chips?  Some of my teammates are reporting issues getting MQ to work on that architecture and just wondering if anyone else has encountered this, gotten to work, or if there is a known incompatibility.  Thanks

**Comment by ibmmqmet** [comment]
The MQ MacOS client package is only available in x64 format. The only ARM-based MQ client is built for Pi. You might be able to get a complete precompiled x64 application running on the M1 via Rosetta conversion, but I don't think you can mix Arm (that might be emitted by the Go compiler) and x64 (the MQ) code in the same process. And I don't know of anyone who has actually tried it. Perhaps use the Go cross-compile options? 

If/when there's a native M1 version of the MQ client then I would expect this Go library to work with it, but not until then. And as far as I know, noone's [submitted any requirements](https://integration-development.ideas.aha.io/?project=MESNS) asking for such a package.

**Comment by irl-segfault** [comment]
Thanks for the update!   Much appreciated

**Comment by ibmmqmet** [comment]
Have you installed the current version of the MQ Developers Toolkit for MacOS before trying to build? That has the M1 support. (It was first released at the end of 2022, so a long time after this issue was originally raised.)

**Comment by adamdecaf** [comment]
Using mq-golang on an M1 mac compiles and works for us. We are seeing those errors when building linux arm docker images though. I don't see a [`cmqc_linux_*.go` file](https://github.com/ibm-messaging/mq-golang/tree/master/ibmmq) for linux and ARM, so the compile error makes sense.

**Comment by ibmmqmet** [comment]
There is not (as of today) any publicly available MQ for Linux arm64 client package. So even with a cqmc*.go file, it wouldn't help as the underlying C libraries could not be found.
