### ISSUE TITLE
How can we specify CCSID 437 on MQMD header before calling .Put method?

### ISSUE THREAD

**Issue by WaqarHassan** [ibm-messaging/mq-golang#178]
_MQ golang version: v5@5.2.0_

Is the following code sample correctly specify CCSID?

```
func send(dst *ibmmq.MQObject, msg []byte, options int32) error {

  putmqmd := ibmmq.NewMQMD()
  pmo := ibmmq.NewMQPMO()
  putmqmd.Format = ibmmq.MQFMT_STRING
  
  putmqmd.CodedCharSetId  = int32(437)
  
  return dst.Put(putmqmd, pmo, msg)

}
```
Thank you.

**Comment by ibmmqmet** [comment]
What happened when you tried it? Did it seem to do the right thing? Did you browse the message to check how it looked on the queue?

**Comment by WaqarHassan** [comment]
Yes. Tested on my local setup of MQ server on Windows. It performed the character set conversion correctly.
thanks.
