### ISSUE TITLE
MQRC_SYNCPOINT_LIMIT_REACHED

### ISSUE THREAD

**Issue by 2020testuser** [ibm-messaging/mq-golang#179]
Hi,
While getting the messages continuously , I'm getting the below error.
Could anyone please let me know whether there is any better way to resolve the error other than modifying the mq setting in the mq server side?

  [ERROR]: Error : "MQGET: MQCC = MQCC_FAILED [2] MQRC = MQRC_SYNCPOINT_LIMIT_REACHED [2024]" 
 

Thanks in advance!

**Comment by ibmmqmet** [comment]
Why are you doing so many operations inside syncpoint? If you really need that number of puts/gets in a single transaction, then changing the MAXUMSGS attribute is the right solution. But more likely, you need to revisit your application code/design to either not use transactions, or commit the transaction after some reasonable batching. [This article](https://developer.ibm.com/articles/an-introduction-to-local-transactions-using-mq-and-jms/) is using the JMS API, but the principles still hold regardless of API.

**Comment by 2020testuser** [comment]
@ibmmqmet - Thanks! I have reduced the waitinterval and the number of threads . Now, I don't get MQRC_SYNCPOINT_LIMIT_REACHED [2024] error. But, I get the below error.

`MQGET: MQCC = MQCC_FAILED [2] MQRC = MQRC_BACKED_OUT [2003]`

Could you please let me know how I can resolve this error?

Regarding MAXUMSGS attribute, yes, I came across when I was reading more on this issue. However, MQ admin don't want to make any changes to the MAXUMSGS attribute.

Anyway to  avoid this error? Also, the application exits when it gets this msg, and so, I need to restart the app.
I will have to reread your article to get all details.
