### ISSUE TITLE
monitor queue manager on prometheus 

### ISSUE THREAD

**Issue by orngeno** [ibm-messaging/mq-golang#18]
Hi
I am new to the premtheus tool. 
I have installed MQ  on windows.
I have installed docker tool box on same path. In docker, i have ran prometheus and grafana docker images.
I can able to access mq objects and perform mqsc commands in dcoker too.
but i need to know how to monitor queue manager from prometheus.
Can you please provide information on this.
![crtmqm in docker](https://user-images.githubusercontent.com/31848376/30364975-f0de4bda-9883-11e7-96cb-b25f12bc6a5c.PNG)

**Comment by ibmmqmet** [comment]
you need to be a lot more specific about what you had problems with. There's no difference connecting to a remote qmgr in Docker compared to any other qmgr, or you can build the docker image containing the monitor configurations and programs along with the qmgr code.
