### ISSUE TITLE
Exporter application handles vs connections

### ISSUE THREAD

**Issue by AlexAlvesJr** [ibm-messaging/mq-golang#181]
Hi Mark!

I have a question: how does this application manage the opening of handle? Does it establishes one connection with the QMGR and opens how many handles it needs to monitoring the objects, or is there a limit of handles per connection?

An example to make it clearer: we have a QMGR that has more than 400 queues. As the exporter must open around 5 handles per queue (connect/disconnect, open/close, put, get and inq/set), we assume that it will need to open more than 2k handles to monitor this environment. However, the maxhands default is 256 and we would have to increase it to 2000 or more, which could expose MQ to applications that work in loop some way.

Thanks a lot,
Alex

**Comment by ibmmqmet** [comment]
See the [metrics README](https://github.com/ibm-messaging/mq-metric-samples/blob/master/README.md) : a single connection is used by the monitor. A warning is given if MAXHANDS is not likely to be big enough. While I can see how managing multiple connections might be possible, it's not something I've got any plans to implement - it would not be a simple change.

**Comment by AlexAlvesJr** [comment]
Thanks, Mark!
