### ISSUE TITLE
How to disable cert revocation check? [9.2.3]

### ISSUE THREAD

**Issue by irl-segfault** [ibm-messaging/mq-golang#182]
Hi all,

I would like to disable certificate revocation checks on the client side, meaning I would like my golang client to not check the revocation status of the queue manager's certificate.  Which flag do I use for this?  I was looking at these docs https://www.ibm.com/docs/en/ibm-mq/9.0?topic=file-ssl-stanza-client-configuration
but cannot map the configuration parameters to anything in the `cmqc` files.  Any help would be appreciated.  Thanks!

**Comment by irl-segfault** [comment]
I'm actually seeing this for the first time
https://www.ibm.com/docs/en/ibm-mq/9.0?topic=file-which-mq-clients-can-read-each-attribute

which details which MQ clients can read which configuration attributes.  Notably, Go is missing, but I'm assuming that for the `ClientRevocationChecks` field, it is also unsupported.  What is not clear is what the actual value ends up being in this case... Assuming it's `REQUIRED` but can't really verify that.  Any help is much appreciated!  Thanks

**Comment by irl-segfault** [comment]
I see, so how can I configure the `ClientRevocationChecks`?  I don't see properties for that anywhere.

**Comment by ibmmqmet** [comment]
The mqclient.ini file is described in the parent topic at https://www.ibm.com/docs/en/ibm-mq/9.2?topic=client-configuring-using-configuration-file in particular the SSL stanza

**Comment by irl-segfault** [comment]
Hoping to re-open this -- I'd like to understand how I can configure the MQ golang client to have some of the properties available in the `mqclient.ini` file.  Is there a way to load such an `ini` file into the Golang client, or is each field exposed in the Go struct on a one-off basis?

**Comment by zemlya25** [comment]
> Hoping to re-open this -- I'd like to understand how I can configure the MQ golang client to have some of the properties available in the `mqclient.ini` file. Is there a way to load such an `ini` file into the Golang client, or is each field exposed in the Go struct on a one-off basis?

Hi! how is your cert battle? Have the same issue during integration with data provider. Have vpn tunnel to ibm, but cert revocation failed during connection. And can't setup extra connection to their server

Checked conn status with mqclient.ini and amqsgetc and it works and validateion can be suppresed according to options in ini

**Comment by zemlya25** [comment]
> Hoping to re-open this -- I'd like to understand how I can configure the MQ golang client to have some of the properties available in the `mqclient.ini` file. Is there a way to load such an `ini` file into the Golang client, or is each field exposed in the Go struct on a one-off basis?

PS. Solved this issue - just set MQCLNTCF env var with path to client config ini file. This seting will be applied on client connect, library connection bindings will use it too/ I suppose it just wraps client calls
