### ISSUE TITLE
How to set Delivery Delay like JMS 2.0

### ISSUE THREAD

**Issue by selseo** [ibm-messaging/mq-golang#187]
I'd like to set Delivery Delay to not put the message to the target queue immediately like setDeliveryDelay method in JMS 2.0 Producer.
I didn't find any document for mq-golang. Is it supported or not?

**Comment by ibmmqmet** [comment]
Unfortunately it's not possbile. That function is only supported today via the JMS API. 

If https://integration-development.ideas.ibm.com/ideas/MESNS-I-88 is ever implemented, then it could be added to other language bindings including Go.
