### ISSUE TITLE
MQ 7.x

### ISSUE THREAD

**Issue by sebgoa** [ibm-messaging/mq-golang#188]
Is there a compatibility mode in this library that could make it usable with a MQ 7.2 instance ?

**Comment by sebgoa** [comment]
7.2 is very very old yes.

We have code that communicates very well with a 9.2 version but for some reason we ran into a 7.2 instance.

Do you think that if we compiled this library with v8 it would work with a v7.2 instance ?

**Comment by ibmmqmet** [comment]
As i said, all versions of MQ can interoperate. You can connect a V9.3 client to a V7.1 qmgr. Of course, things like a TLS connection might not work because of different cipher availability. And whether your program actually works will depend on if it uses any features that only came in later.

**Comment by sebgoa** [comment]
English is not my first language so you have to excuse me if I don't understand you right away.
