### ISSUE TITLE
Listing MQ Queues and which Clusters they belong to ? 

### ISSUE THREAD

**Issue by leondelange123** [ibm-messaging/mq-golang#191]
Hello Mark, 

I was wondering if at all possible to perhaps include the CLUSTER a queue belongs to per queue manager. We use Grafana and this exporter heavily at our site and it would be very handy if we could tell which cluster a queue belongs to. 

We are looking to setup a self service portal and need some of this info and since you done such brilliant job already getting all the other data how about including cluster name please. 

Thanks
Leon De Lange
ABSA Bank

**Comment by ibmmqmet** [comment]
Adding the single cluster tag sounds reasonable. I'll take a look for the next set of updates. 

But I wouldn't expect to deal with CLUSTERNL resolution, where a queue might be a member of multiple clusters (just as the qmgr cluster status already here similarly doesn't report CLUSTERNL settingds).

**Comment by leondelange123** [comment]
Morning,  Yes spot on... All I'm after is a way to see which cluster a queue belongs to in a queue manager.  That way with Grafana I can build a view of clusters and which queues belong to which cluster. 
This will be extremely valuable and would really help in our self services journey. 


Example.... Add the CLUSTER to the exporter metrics... So in Grafana I can say list all queue in the "QU.CLUSTER" and the QMGR will be there already I guess.

display qlocal('CURO.INTERFACE.CLIENT.QLCL.AWD') CLUSTER
     6 : display qlocal('CURO.INTERFACE.CLIENT.QLCL.AWD') CLUSTER
AMQ8409I: Display Queue details.
   QUEUE(CURO.INTERFACE.CLIENT.QLCL.AWD)   TYPE(QLOCAL)
   **CLUSTER(QU.CLUSTER)**



Thanks for looking Mark...

**Comment by ibmmqmet** [comment]
Added a "cluster" tag in latest version

**Comment by leondelange123** [comment]
Thanks very much Mark. I have complied last night and it's working great. Again thanks for a speedy response.
