### ISSUE TITLE
Not sharing Session when multi connecting to an SSL channel

### ISSUE THREAD

**Issue by alex3dm** [ibm-messaging/mq-golang#194]
<img width="1067" alt="Снимок экрана 2022-11-24 в 12 43 31" src="https://user-images.githubusercontent.com/4047685/203735698-a5ad67a3-a2c6-49fd-a5f3-73f00009fe36.png">
Hello
Not sharing Session when multi connecting to an SSL channel

- Version  MQ - 9.2, 
- Version MQ client - 9.2.0.1
- mq-golang - latest
- Go compiler - 15.1

**Comment by ibmmqmet** [comment]
I have absolutely no idea what you are asking here.

**Comment by seminmw** [comment]
I have this problem too. When we run the ibmmq.Connx(qMgrName, cno) function, a separate connection is created for each call. Each connection has 10 dialogs. I want 10 connections to connect through 1 physical dialog, not create 10 separate connections. Can you help with this problem?
Example:
<img width="1058" alt="Снимок экрана 2022-11-23 в 17 08 09" src="https://user-images.githubusercontent.com/25885279/203932985-b4520253-925d-4b0a-a967-03dc00e9812d.png">

**Comment by alex3dm** [comment]
@ibmmqmet  up(seminmv) described in more detail

**Comment by ibmmqmet** [comment]
You've still not given ANY detail. A single screenshot is not a problem description.

What is the configuration? 
What is the application program doing? 
What are you expecting to see?
Have you read the product documentation such as [this](https://www.ibm.com/docs/en/ibm-mq/9.3?topic=cbdvmmcqm-mqi-client-default-behavior-client-connection-server-connection-channels) that describes how to use SHRCONV?

**Comment by alex3dm** [comment]
Found a solution
the problem was in parameter passing - SSLPeerName
mqiMQCD.go
func copyCDtoC(mqcd *C.MQCD, gocd *MQCD) {
...
  if gocd.SSLPeerName != "" {
		mqcd.SSLPeerNamePtr = C.MQPTR(unsafe.Pointer(C.CString(gocd.SSLPeerName)))
with multiple connections, you need to cache the link to C.MQPTR(unsafe.Pointer(C.CString(gocd.SSLPeerName)))
