### ISSUE TITLE
Grafana and Prometheus IBM MQ metric for total messages count.

### ISSUE THREAD

**Issue by maggimedha** [ibm-messaging/mq-golang#195]
Please include the following information in your ticket.

- Version information for MQ, mq-golang, Go compiler
- A small code sample that demonstrates the issue.

We are trying to get total IBM MQ messages count report in Queue manager using Prometheus and grafana monitoring. Could you please help us to get grafana metric for messages total count.

**Comment by ibmmqmet** [comment]
Dup of ibm-messaging/mq-metric-samples#199
