### ISSUE TITLE
Does this work with MQ8

### ISSUE THREAD

**Issue by nsupathy** [ibm-messaging/mq-golang#2]
Is it possible to make this work with MQ8 by reading the statistics out of the queue rather than subscribing to it (as in MQ9)

**Comment by ibmmqmet** [comment]
It would be possible to write a similar program that handled those statistics messages, but the content is different than the pub/sub messages, and would need to be processed slightly differently. These particular monitor programs cannot work with them unchanged, though parts of them would form a reasonable basis of a new program.

The amqsmon sample formats those messages, as does SupportPac MS0P.
