### ISSUE TITLE
Manual message acknowledge

### ISSUE THREAD

**Issue by Apcenuu** [ibm-messaging/mq-golang#201]
In IBM MQ we have XMSC_AUTO_ACKNOWLEDGE mode and XMSC_CLIENT_ACNOWLEDGE mode. But library uses autoacknowledge. I dont find in samples and sources how to use manual ack mode. Its possible?

**Comment by ibmmqmet** [comment]
Thiose are JMS/XMS concepts, not MQI. The approximate equivalent in the core MQI is to use transactions - the Put/Get options for SYNCPOINT with a Cmit() call.
