### ISSUE TITLE
User

### ISSUE THREAD

**Issue by brockram17** [ibm-messaging/mq-golang#202]
Hi, Does it really need to be the default mqm user to run this or I can give a different user?

**Comment by ibmmqmet** [comment]
To run what? The main part of this repo is simply an API for you to write your own applications.

Applications can run under any id - you just need to authorise them in the usual MQ way

**Comment by brockram17** [comment]
Thanks. 
To run the mq go exporter itself, so I can pick any user and create OAM on that user for the qmgr, run it and it should work?

**Comment by ibmmqmet** [comment]
Monitoring programs can run under any userid that has appropriate authorisations.

**Comment by brockram17** [comment]
Thanks, Just wanted to know there is no coupling.  I will get back if any further questions.
