### ISSUE TITLE
fatal error: unexpected signal during runtime execution [signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f600d01c414]

### ISSUE THREAD

**Issue by nowayout** [ibm-messaging/mq-golang#21]
`package main

import (
    "bufio"
    "fmt"
    "../ibmmq"
    "os"
    "strings"
    // "time"
)

func main() {
    var qMgrName string
    var qMgrObject ibmmq.MQObject
    var managedQObject ibmmq.MQObject
    var subObject ibmmq.MQObject
    var err error
    var qMgr ibmmq.MQQueueManager
    // var rc int
    var openOptions int32
    var qObject ibmmq.MQObject

if len(os.Args) != 5 {
    fmt.Println("clientconn <qmgrname> <channelname> <conname> <queuename>")
    fmt.Println("")
    fmt.Println("For example")
    fmt.Println("  clientconn QMGR1 \"SYSTEM.DEF.SVRCONN\" \"myhost.example.com(1414)\" \"LOCAL.QUEUE\"")
    fmt.Println("All parameters are required.")
    os.Exit(1)
}

connected := false

qMgrName = os.Args[1]

cno := ibmmq.NewMQCNO()
cd := ibmmq.NewMQCD()

cd.ChannelName = os.Args[2]
cd.ConnectionName = os.Args[3]

cno.ClientConn = cd
cno.Options = ibmmq.MQCNO_CLIENT_BINDING

userId := os.Getenv("MQSAMP_USER_ID")
if userId != "" {
    scanner := bufio.NewScanner(os.Stdin)
    csp := ibmmq.NewMQCSP()
    csp.AuthenticationType = ibmmq.MQCSP_AUTH_USER_ID_AND_PWD
    csp.UserId = userId

    fmt.Println("Enter password : ")
    scanner.Scan()
    csp.Password = scanner.Text()

    cno.SecurityParms = csp
}

qMgr, err = ibmmq.Connx(qMgrName, cno)
// qMgr, err = ibmmq.Conn(qMgrName)
if err == nil {
    fmt.Printf("Connection to %s succeeded.\n", qMgrName)
    // d, _ := time.ParseDuration("5s")
    // time.Sleep(d)
    // qMgr.Disc()
} else {
    fmt.Printf("Connection to %s failed.\n", qMgrName)
    fmt.Println(err)
}

if err == nil {
    mqod := ibmmq.NewMQOD()

    openOptions = ibmmq.MQOO_OUTPUT + ibmmq.MQOO_FAIL_IF_QUIESCING
    openOptions |= ibmmq.MQOO_INPUT_AS_Q_DEF

    mqod.ObjectType = ibmmq.MQOT_Q
    mqod.ObjectName = os.Args[4]

    qObject, err = qMgr.Open(mqod, openOptions)
    if err != nil {
        fmt.Println(err)
    } else {
        fmt.Println("Opened queue", qObject.Name)
    }
}

if err == nil {
    putmqmd := ibmmq.NewMQMD()
    pmo := ibmmq.NewMQPMO()

    pmo.Options = ibmmq.MQPMO_SYNCPOINT | ibmmq.MQPMO_NEW_MSG_ID | ibmmq.MQPMO_NEW_CORREL_ID

    putmqmd.Format = "MQSTR"
    msgData := "Hello from Go"
    buffer := []byte(msgData)

    // mqod := ibmmq.NewMQOD()
    // openOptions = ibmmq.MQOO_INQUIRE + ibmmq.MQOO_FAIL_IF_QUIESCING
    // mqod.ObjectType = ibmmq.MQOT_CHANNEL
    // mqod.ObjectName = qObject.Name
    err = qObject.Put(putmqmd, pmo, buffer)
    // err = qMgr.Put1(mqod, putmqmd, pmo, buffer)

    if err != nil {
        fmt.Println(err)
    } else {
        fmt.Println("Put message to", qObject.Name)
    }
}

if err == nil {
    err = qMgr.Cmit()
    if err != nil {
        fmt.Println(err)
    }
}

if err == nil {
    msgAvail := true

    for msgAvail == true {
        var datalen int

        getmqmd := ibmmq.NewMQMD()
        gmo := ibmmq.NewMQGMO()
        gmo.Options = ibmmq.MQGMO_NO_SYNCPOINT | ibmmq.MQGMO_FAIL_IF_QUIESCING
        gmo.Options |= ibmmq.MQGMO_WAIT
        gmo.WaitInterval = 3000
        buffer := make([]byte, 32768)

        datalen, err = qObject.Get(getmqmd, gmo, buffer)

        if err != nil {
            msgAvail = false
            fmt.Println(err)
            mqret := err.(*ibmmq.MQReturn)
            if mqret.MQRC == ibmmq.MQRC_NO_MSG_AVAILABLE {
                err = nil
            }
        } else {
            fmt.Printf("Got message of length %d: ", datalen)
            fmt.Println(strings.TrimSpace(string(buffer[:datalen])))
        }
    }
}

if err == nil {
    err = qObject.Close()
    if err != nil {
        fmt.Println(err)
    } else {
        fmt.Println("Closed queue")
    }
}

if err == nil {
    mqsd := ibmmq.NewMQSD()
    mqsd.Options = ibmmq.MQSO_CREATE
    mqsd.Options |= ibmmq.MQSO_NON_DURABLE
    mqsd.Options |= ibmmq.MQSO_FAIL_IF_QUIESCING
    mqsd.Options |= ibmmq.MQSO_MANAGED
    mqsd.ObjectString = "$SYS/MQ/INFO/QMGR/" + qMgrName + "/ActivityTrace/ApplName/mqitest"

    subObject, err = qMgr.Sub(mqsd, &managedQObject)

    if err != nil {
        fmt.Println(err)
    } else {
        fmt.Println("Subscribed to topic ", mqsd.ObjectString)
    }
}

if err == nil {
    msgAvail := true

    for msgAvail == true {
        var datalen int

        getmqmd := ibmmq.NewMQMD()
        gmo := ibmmq.NewMQGMO()
        gmo.Options = ibmmq.MQGMO_NO_SYNCPOINT | ibmmq.MQGMO_FAIL_IF_QUIESCING
        gmo.Options |= ibmmq.MQGMO_WAIT
        gmo.WaitInterval = 3000
        buffer := make([]byte, 32768)

        datalen, err = managedQObject.Get(getmqmd, gmo, buffer)

        if err != nil {
            msgAvail = false
            fmt.Println(err)
            mqret := err.(*ibmmq.MQReturn)
            if mqret.MQRC == ibmmq.MQRC_NO_MSG_AVAILABLE {
                // not a real error so reset err, but
                // end retrieval loop
                err = nil
            }
        } else {
            fmt.Printf("Got message of length %d. Format = %s\n", datalen, getmqmd.Format)
        }
    }
}

if err == nil {
    subObject.Close()
}

if err == nil {
    mqod := ibmmq.NewMQOD()
    openOptions = ibmmq.MQOO_INQUIRE + ibmmq.MQOO_FAIL_IF_QUIESCING

    mqod.ObjectType = ibmmq.MQOT_Q_MGR
    mqod.ObjectName = qMgrName

    qMgrObject, err = qMgr.Open(mqod, openOptions)

    if err != nil {
        fmt.Println(err)
    } else {
        fmt.Printf("Opened QMgr for MQINQ\n")
    }
}

if err == nil {
    selectors := []int32{ibmmq.MQCA_Q_MGR_NAME,
        ibmmq.MQCA_DEAD_LETTER_Q_NAME,
        ibmmq.MQIA_MSG_MARK_BROWSE_INTERVAL}

    intAttrs, charAttrs, err := qMgrObject.Inq(selectors, 2, 160)

    if err != nil {
        fmt.Println(err)
    } else {
        returnedName := string(charAttrs[0:48])
        fmt.Printf("MQINQ returned +%v %s \n",
            intAttrs, string(charAttrs))
        fmt.Printf("               '%s'\n", returnedName)
    }

}

if connected {
    err = qMgr.Disc()
    fmt.Println("Disconnected from queue manager ", qMgrName)
}

if err == nil {
    os.Exit(0)
} else {
    mqret := err.(*ibmmq.MQReturn)
    os.Exit((int)(mqret.MQCC))
}

}`

But it get the following error:
`> [root@localhost clientconn]# ./clientconn QM_T01 "JMS" "127.0.0.1(1414)" "LQ"
Connection to QM_T01 succeeded.
Opened queue LQ
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f214ba2b414]
> 
> runtime stack: runtime.throw(0x4ebdce, 0x2a)
>   /home/app/go/src/runtime/panic.go:605 +0x95 runtime.sigpanic()
>   /home/app/go/src/runtime/signal_unix.go:351 +0x2b8
> 
> goroutine 1 [syscall, locked to thread]: runtime.cgocall(0x49ed30,
> 0xc42004f9c8, 0x100)  /home/app/go/src/runtime/cgocall.go:132 +0xe4
> fp=0xc42004f980 sp=0xc42004f940 pc=0x4072c4
> _/svr/ibmmq/ibmmq._Cfunc_MQPUT(0x1000006, 0xc42007c000, 0xc4200720c0, 0xd, 0xc420016110, 0xc420016120, 0xc4200160fc)
>   _/svr/ibmmq/ibmmq/_obj/_cgo_gotypes.go:887 +0x45 fp=0xc42004f9c8
> sp=0xc42004f980 pc=0x4938e5
> _/svr/ibmmq/ibmmq.MQObject.Put.func1(0x1000006, 0xc42007c000, 0xc4200720c0, 0xc40000000d, 0xc420016110, 0xc420016120, 0xc4200160fc)
>   /svr/ibmmq/ibmmq/mqi.go:407 +0x10e fp=0xc42004fa10 sp=0xc42004f9c8
> pc=0x49a69e
> _/svr/ibmmq/ibmmq.MQObject.Put(0x0, 0xc42000c0a0, 0xc42001a0f0, 0x30, 0xc420078000, 0xc42007a000, 0xc420016110, 0xd, 0x10, 0x0, ...)
>   /svr/ibmmq/ibmmq/mqi.go:407 +0x120 fp=0xc42004fa80 sp=0xc42004fa10
> pc=0x495030 main.main()   /svr/ibmmq/clientconn/clientconn.go:102
> +0x158e fp=0xc42004ff80 sp=0xc42004fa80 pc=0x49e29e runtime.main()    /home/app/go/src/runtime/proc.go:195 +0x226 fp=0xc42004ffe0
> sp=0xc42004ff80 pc=0x42e9c6 runtime.goexit()
>   /home/app/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42004ffe8
> sp=0xc42004ffe0 pc=0x457491`

**Comment by ibmmqmet** [comment]
The program above does not actually compile (the Close() functions need a parameter), but when I correct that, the program runs OK for me. If you are able to run incorrect code that makes me wonder about the level of Go and supporting modules that you have installed. If the SEGV actually comes from within the MQ librariy, then perhaps there's an FDC generated in the MQ errors directory.

**Comment by nowayout** [comment]
`[root@localhost clientconn]# GOTRACEBACK=crash GODEBUG=cgocheck=1 ./clientconn QM_T01 "JMS" "192.168.1.236(1414)" "LQ"
Connection to QM_T01 succeeded.
Opened queue LQ
Put message to LQ
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7fda47fae414]

runtime stack:
runtime.throw(0x4e81dd, 0x2a)
	/home/app/go/src/runtime/panic.go:605 +0x95 fp=0x7fff507d85d0 sp=0x7fff507d85b0 pc=0x42d255
runtime.sigpanic()
	/home/app/go/src/runtime/signal_unix.go:351 +0x2b8 fp=0x7fff507d8620 sp=0x7fff507d85d0 pc=0x440348

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x49bda0, 0xc42004fc60, 0x4)
	/home/app/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc42004fc20 sp=0xc42004fbe0 pc=0x407244
_/svr/ibmmq/mq-golang/ibmmq._Cfunc_MQCMIT(0x1000006, 0xc420016164, 0xc420016160)
	_/svr/ibmmq/mq-golang/ibmmq/_obj/_cgo_gotypes.go:684 +0x45 fp=0xc42004fc60 sp=0xc42004fc20 pc=0x492fb5
_/svr/ibmmq/mq-golang/ibmmq.(*MQQueueManager).Cmit(0xc42000c0c0, 0x2, 0x2)
	/svr/ibmmq/mq-golang/ibmmq/mqi.go:317 +0x6e fp=0xc42004fca0 sp=0xc42004fc60 pc=0x49421e
main.main()
	/svr/ibmmq/mq-golang/clientconn/clientconn.go:148 +0x844 fp=0xc42004ff80 sp=0xc42004fca0 pc=0x49b4f4
runtime.main()
	/home/app/go/src/runtime/proc.go:195 +0x226 fp=0xc42004ffe0 sp=0xc42004ff80 pc=0x42e946
runtime.goexit()
	/home/app/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42004ffe8 sp=0xc42004ffe0 pc=0x457761

goroutine 2 [force gc (idle)]:
runtime.gopark(0x4e97c8, 0x7a7eb0, 0x4e37b2, 0xf, 0x14, 0x1)
	/home/app/go/src/runtime/proc.go:287 +0x12c fp=0xc42002a768 sp=0xc42002a738 pc=0x42edfc
runtime.goparkunlock(0x7a7eb0, 0x4e37b2, 0xf, 0xc420000114, 0x1)
	/home/app/go/src/runtime/proc.go:293 +0x5e fp=0xc42002a7a8 sp=0xc42002a768 pc=0x42eeee
runtime.forcegchelper()
	/home/app/go/src/runtime/proc.go:245 +0xcc fp=0xc42002a7e0 sp=0xc42002a7a8 pc=0x42ec1c
runtime.goexit()
	/home/app/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42002a7e8 sp=0xc42002a7e0 pc=0x457761
created by runtime.init.4
	/home/app/go/src/runtime/proc.go:234 +0x35

goroutine 3 [GC sweep wait]:
runtime.gopark(0x4e97c8, 0x7a7fc0, 0x4e3352, 0xd, 0x422614, 0x1)
	/home/app/go/src/runtime/proc.go:287 +0x12c fp=0xc42002af60 sp=0xc42002af30 pc=0x42edfc
runtime.goparkunlock(0x7a7fc0, 0x4e3352, 0xd, 0x14, 0x1)
	/home/app/go/src/runtime/proc.go:293 +0x5e fp=0xc42002afa0 sp=0xc42002af60 pc=0x42eeee
runtime.bgsweep(0xc420054000)
	/home/app/go/src/runtime/mgcsweep.go:52 +0xa3 fp=0xc42002afd8 sp=0xc42002afa0 pc=0x422633
runtime.goexit()
	/home/app/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42002afe0 sp=0xc42002afd8 pc=0x457761
created by runtime.gcenable
	/home/app/go/src/runtime/mgc.go:216 +0x58

goroutine 4 [finalizer wait]:
runtime.gopark(0x4e97c8, 0x7c62b8, 0x4e35be, 0xe, 0x14, 0x1)
	/home/app/go/src/runtime/proc.go:287 +0x12c fp=0xc42002b700 sp=0xc42002b6d0 pc=0x42edfc
runtime.goparkunlock(0x7c62b8, 0x4e35be, 0xe, 0x14, 0x1)
	/home/app/go/src/runtime/proc.go:293 +0x5e fp=0xc42002b740 sp=0xc42002b700 pc=0x42eeee
runtime.runfinq()
	/home/app/go/src/runtime/mfinal.go:175 +0xb8 fp=0xc42002b7e0 sp=0xc42002b740 pc=0x419698
runtime.goexit()
	/home/app/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42002b7e8 sp=0xc42002b7e0 pc=0x457761
created by runtime.createfing
	/home/app/go/src/runtime/mfinal.go:156 +0x62

goroutine 5 [timer goroutine (idle)]:
runtime.gopark(0x4e97c8, 0x7a8160, 0x4e4ccd, 0x16, 0x14, 0x1)
	/home/app/go/src/runtime/proc.go:287 +0x12c fp=0xc42002bf20 sp=0xc42002bef0 pc=0x42edfc
runtime.goparkunlock(0x7a8160, 0x4e4ccd, 0x16, 0x14, 0x1)
	/home/app/go/src/runtime/proc.go:293 +0x5e fp=0xc42002bf60 sp=0xc42002bf20 pc=0x42eeee
runtime.timerproc()
	/home/app/go/src/runtime/time.go:208 +0x27b fp=0xc42002bfe0 sp=0xc42002bf60 pc=0x44911b
runtime.goexit()
	/home/app/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42002bfe8 sp=0xc42002bfe0 pc=0x457761
created by runtime.addtimerLocked
	/home/app/go/src/runtime/time.go:122 +0xed
已放弃 (core dumped)
[root@localhost clientconn]# `

**Comment by ibmmqmet** [comment]
Closing for lack of followup detail. Not reproducible here.
