### ISSUE TITLE
fatal error: cmqc.h: No such file or directory -- any help on resolving this

### ISSUE THREAD

**Issue by sudhakaranemu** [ibm-messaging/mq-golang#22]
[jssudha@jsrlinux7 jsgowork]$ go install ./src/cmd/mq_prometheus 
# ibmmq
src/ibmmq/mqi.go:57:18: fatal error: cmqc.h: No such file or directory
 #include <cmqc.h>
                  ^
compilation terminated.
[jssudha@jsrlinux7 jsgowork]$ ls
pkg  src
[jssudha@jsrlinux7 jsgowork]$

**Comment by MSH82** [comment]
Hi,

Were you able to solve this problem ? Can you please post the solution here ?

**Comment by lladhibhutall** [comment]
Can you please tell me the solution to this problem? go version 1.12.5

**Comment by sumitbsn** [comment]
For fixing this issue ibmmq-client and ibmmq-sdk packages needs to be installed. 

1. IBM MQADV pkgs list: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/
2. https://developer.ibm.com/components/ibm-mq/tutorials/mq-connect-app-queue-manager-ubuntu/
3. Install ibmmq-clinet and ibmmq-sdk packages

**Comment by perplex2016** [comment]
Can you please tell me the solution to this problem?

**Comment by sumitbsn** [comment]
@perplex2016 You can follow below steps to fix this issue.

1. Download latest mqadv tar file from below link and extract it
    IBM MQADV pkgs list: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/
2. setup local repo for installing ibmmq-clinet and ibmmq-sdk packages
3. Install packges ibmmq-clinet and ibmmq-sdk

If you didn't get the above steps then search on google how to install IBM MQ client and ibmmq-sdk packages and follow the steps.

**Comment by vivek-arya-od** [comment]
Looks like the MQADV files are NOT available for MAC. Any directions here?
