### ISSUE TITLE
go build ibmmq: invalid flag in #cgo LDFLAGS: -Wl,-rpath=/opt/mqm/lib64

### ISSUE THREAD

**Issue by ycao56** [ibm-messaging/mq-golang#23]
I am getting following errors when trying to compile the project

```
go build ibmmq: invalid flag in #cgo LDFLAGS: -Wl,-rpath=/opt/mqm/lib64
```

**Comment by ibmmqmet** [comment]
The Go compiler was recently changed to disallow most flags by default for security reasons.
See https://golang.org/cmd/cgo  You need to set an environment variable to override this behaviour.

    export CGO_LDFLAGS_ALLOW="-Wl,-rpath.*"
