### ISSUE TITLE
Question: prometheus - mq channel statistic

### ISSUE THREAD

**Issue by andywow** [ibm-messaging/mq-golang#25]
Do you have plans to realize collection of mq channel statistic metrics in prometheus exporter?

**Comment by ibmmqmet** [comment]
If you look at the current prometheus code, you'll see a few foundation steps are visible towards doing something with channel info (based on the DISPLAY CHSTATUS output). It's not used at the moment and is nowhere near complete, but it's something I'd like to finish at some point. Though I'm not going to promise if or when.

**Comment by ibmmqmet** [comment]
Channel status and tiny amount of statistics are now available in the prometheus monitor. Please see if that gives useful information.
