### ISSUE TITLE
Build failed with undefined: mqmetric.InitChlStatistics

### ISSUE THREAD

**Issue by P9110963** [ibm-messaging/mq-golang#27]
Go build failed with the below exceptions. As I could see the channel statistics are recently added as part of updated 905 branch. Kindly shed some light on further proceedings. 

# command-line-arguments
src/cmd/mq_prometheus/main.go:76: undefined: mqmetric.InitChlStatistics
The command '/bin/sh -c cd $HOME      && export PATH=$PATH:/usr/local/go/bin      && export GOPATH=$HOME      && go build -o /usr/local/bin/mq_prometheus src/cmd/mq_prometheus/*.go' returned a non-zero code: 2

**Comment by ibmmqmet** [comment]
The code still had a reference to an un-checked in file (so it built fine in my tree). I've commented it out for now and repushed.

**Comment by P9110963** [comment]
Thanks. It is working now. :)
