### ISSUE TITLE
How to use application after build?

### ISSUE THREAD

**Issue by mister87** [ibm-messaging/mq-golang#3]
Hi!
After build application and runing with other PC there is an error MQRC 2277.

Environment is possibly not correctly set. How it is correct to launch? MQ Client is set.

**Comment by ibmmqmet** [comment]
Back in the office after some time out ...

MQRC 2277 is MQRC_CD_ERROR which suggests something wrong like an environment variable pointing to a bad Client Channel Table perhaps.

Is this your own program using the API? Or one of the provided programs? Which version of MQ are you building against? 

The various monitors need the ibmmq.client flag on the command line to indicate it is a client connection; the simplest way of pointing at a remote qmgr is using the MQSERVER environment variable.
