### ISSUE TITLE
MQ Client version

### ISSUE THREAD

**Issue by timrawson** [ibm-messaging/mq-golang#4]
When i do go install ./src/ibmmq (assuming this what want to build if want the basic MQ client go package).... I get
```
# ibmmq
src/ibmmq/mqiMQCNO.go:126: mqcno.CCDTUrlOffset undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlOffset)
src/ibmmq/mqiMQCNO.go:128: mqcno.CCDTUrlPtr undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlPtr)
src/ibmmq/mqiMQCNO.go:129: mqcno.CCDTUrlLength undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlLength)
src/ibmmq/mqiMQCNO.go:131: mqcno.CCDTUrlPtr undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlPtr)
src/ibmmq/mqiMQCNO.go:132: mqcno.CCDTUrlLength undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlLength)
src/ibmmq/mqiMQCNO.go:149: mqcno.CCDTUrlPtr undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlPtr)
src/ibmmq/mqiMQCNO.go:150: mqcno.CCDTUrlPtr undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlPtr)
```

Looked at the tagMQCNO struct in the mq includes, and do not see any struct members with Url in it.  I am using MQ client linux 8.0.5.  Though am a go noob.

**Comment by jgrusewski** [comment]
Hi,

I'm running the same version, getting the exact same error:

`./mqiMQCNO.go:125: mqcno.CCDTUrlOffset undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlOffset)
./mqiMQCNO.go:127: mqcno.CCDTUrlPtr undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlPtr)
./mqiMQCNO.go:128: mqcno.CCDTUrlLength undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlLength)
./mqiMQCNO.go:130: mqcno.CCDTUrlPtr undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlPtr)
./mqiMQCNO.go:131: mqcno.CCDTUrlLength undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlLength)
./mqiMQCNO.go:149: mqcno.CCDTUrlPtr undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlPtr)
./mqiMQCNO.go:150: mqcno.CCDTUrlPtr undefined (type *C.struct_tagMQCNO has no field or method CCDTUrlPtr)`

**Comment by ibmmqmet** [comment]
The CCDT URL feature was added in MQ V9. Unfortunately, Go doesn't have a granular conditional compile capability where I could use something like #if to check the current version at build time. So to compile against older levels of MQ you'd have to remove those lines from the MQCNO processing. (But I can't think of anything else that wouldn't work with V8.)

**Comment by timrawson** [comment]
Downloaded MQ v9 trial and was able to build.

Though now have a question, maybe some ignorance on the core MQ since most of time communicate to MQ via JMS/Java....    trying to run the mqitest, have to pass in queue name and queuemanager name, which know.  However it is not local to the machine and uncertain how to provide IP, port (not std 1414) and username password.   Some digging around see things like: export  MQSERVER='ChannelName/TransportType/ConnectionName'....   Guess easier to just ask, how to provide ip, port, user/pw?

**Comment by ibmmqmet** [comment]
http://www.ibm.com/support/knowledgecenter/SSFKSJ_8.0.0/com.ibm.mq.con.doc/q016990_.htm shows the syntax of the MQSERVER environment variable which is the simplest way to get client connectivity (no support with that for TLS etc which would be have to be set in a CCDT file). For example 
`
export` MQSERVER="SYSTEM.DEF.SVRCONN/TCP/myhost.example.com(2424)"

Setting userid/password has to be done in the application code, similar to the amqsput0.c sample program (create MQCSP, fill  it in with the values, create MQCNO, point the CNO field at the CSP).

I've not tried the mqitest as-is as a client connection; that was always tested against a local queue manager. It might need modifications in the same way as the larger monitoring programs to use MQCONNX and a CNO with the options field set to indicate client mode.
