### ISSUE TITLE
How to get message commit time?

### ISSUE THREAD

**Issue by rudygunawan** [ibm-messaging/mq-golang#5]
Hi. Thank you for providing this library.  Is it possible to get the message commit timestamp ? I know that I can get PutTime easily from mqmd, but I'm looking for a way to get commit timestamp from Get method like below.

      datalen, mqreturn, err = qObject.Get(getmqmd, gmo, buffer)

**Comment by ibmmqmet** [comment]
I don't know what you mean by the commit time. The MQMD structure does contain the PutDate and PutTime (which is not necessarily the same as when a transaction was committed).
