### ISSUE TITLE
Support for New Relic reporting

### ISSUE THREAD

**Issue by asomensari** [ibm-messaging/mq-golang#50]
I am working on adding another option for reporting the collected data (send to New Relic). How should I proceed? Should I just send a PR?

**Comment by ibmmqmet** [comment]
If you look at the dev branch, you will see that the monitor programs have been moved to a separate repository - [mq-metric-samples](https://github.com/ibm-messaging/mq-metric-samples) - along with a couple of changes to how the core MQ libraries are referenced. 

PRs could be sent into that repo with the usual requirement of accepting the Contributor Agreement.
