### ISSUE TITLE
mq-golang and mqmetric build

### ISSUE THREAD

**Issue by sagar123ramesh** [ibm-messaging/mq-golang#56]
Dear ibm-messaging team,

I'm trying to build mq-golang and mqmetric from the following trees.  However, the instructions provided in README files are provided in the below git URLs are not working as is. 

- MQ V9.0.0.2  ( I hope this MQ level is supported by mq-golang and mqmetric?)
- mq-golang https://github.com/ibm-messaging/mq-golang/tree/v2.0.0
- mq-metric-samples https://github.com/ibm-messaging/mq-metric-samples
- go version go1.10.3 linux/amd64  on RHEL 7.3

I see the directory structure I have (source is downloaded through "Clone or Download" button) doesn't match with what is provided in the build instructions. 

Is there a way to download already compiled binaries?  That will really help OR any reference to build instruction also will do.  Please do the needful. Thanks in advance.

**Comment by salapat11** [comment]
Were you able to get it working @sagar123ramesh ?

If so, can you please share which versions of go-lang and samples you used?  We are trying to leverage mq_prometheus to collect the stats.

**Comment by ibmmqmet** [comment]
Build instructions in both of these Go repositories have been reviewed and modified. Following them should produce the binaries. I was able to start from an empty directory tree and successfully compile the code.
