### ISSUE TITLE
Error down load the project from git

### ISSUE THREAD

**Issue by xeccgtt** [ibm-messaging/mq-golang#6]
We are trying to execute go get -u github.com/prometheus/client_golang on a windows 7 PC.    WE are getting the following error, 

It appears that https://github.com/prometheus/client_golang/info/refs is a broken link. 

Do ou have any insight on what we aredoing wrong. 

M:\APM\mq_promo_monitoring>**go get -u github.com/prometheus/client_golang**

# cd .; git clone https://github.com/prometheus/client_golang M:\APM\mq_promo_monitoring\src\github.com\prometheus\clien
t_golang
Cloning into 'M:\APM\mq_promo_monitoring\src\github.com\prometheus\client_golang'...
fatal: https://github.com/prometheus/client_golang/info/refs _not valid: is this a git repository_?
package github.com/prometheus/client_golang: **exit status 128**

**Comment by ibmmqmet** [comment]
Perhaps because your command is missing the final "prometheus".

go get -u github.com/prometheus/client_golang/prometheus

That works fine for me.

**Comment by xeccgtt** [comment]
Hi,  your suggestion did not work. We are still getting the same error when we run :

·         go get -u github.com/prometheus/client_golang/prometheus

M:\APM\mq_promo_monitoring> go get -u github.com/prometheus/client_golang/prometheus
# cd .; git clone https://github.com/prometheus/client_golang M:\APM\mq_promo_monitoring\src\github.com\prometheus\client_golang
Cloning into 'M:\APM\mq_promo_monitoring\src\github.com\prometheus\client_golang'...
fatal: https://github.com/prometheus/client_golang/info/refs not valid: is this a git repository?
package github.com/prometheus/client_golang/prometheus: exit status 128

**Comment by xeccgtt** [comment]
By the way we are following the instructions from this web page.

·         https://www.ibm.com/developerworks/community/blogs/messaging/entry/IBM_MQ_Using_Prometheus_and_Grafana_to_montor_queue_managers?lang=en

Are we missing some sort of dependency.

From: Stark, Albert J
Sent: Wednesday, December 14, 2016 6:29 AM
To: 'ibm-messaging/mq-golang'; ibm-messaging/mq-golang
Cc: Author
Subject: RE: [ibm-messaging/mq-golang] Error down load the project from git (#6)


Hi,  your suggestion did not work. We are still getting the same error when we run :

·         go get -u github.com/prometheus/client_golang/prometheus

M:\APM\mq_promo_monitoring> go get -u github.com/prometheus/client_golang/prometheus
# cd .; git clone https://github.com/prometheus/client_golang M:\APM\mq_promo_monitoring\src\github.com\prometheus\client_golang
Cloning into 'M:\APM\mq_promo_monitoring\src\github.com\prometheus\client_golang'...
fatal: https://github.com/prometheus/client_golang/info/refs not valid: is this a git repository?
package github.com/prometheus/client_golang/prometheus: exit status 128

**Comment by ibmmqmet** [comment]
The README in the root of this repo contains fuller instructions on downloading various components. Possibly you need to rerun from an empty directory - anything hanging around from a previous attempt may be confusing the clone process, since your error message still refers to a parent directory. As I said, running that get -u command worked this morning on my system.

**Comment by xeccgtt** [comment]
We are getting a 404 when we go to this page  https://github.com/ibm-messaging/mq-golang/info/refs

I wiped out the .git directory and src directory on my PC. I reinitialized git by doing git init.

The git clone from the web page is failing
M:\APM\mq_promo_monitoring>git clone http://github.com/ibm-messaging/mq-golang
Cloning into 'mq-golang'...
fatal: https://github.com/ibm-messaging/mq-golang/info/refs not valid: is this a git repository?

Any idea why git clone is failing on my windows 7 PC.


[cid:image001.png@01D255D8.267E1620]

**Comment by ibmmqmet** [comment]
All I can imagine is you've got a bad (perhaps downlevel?) git program.

My Windows system has
   git --version
  git version 2.9.0.windows.1

Googling for the error message has several suggestions. But versioning appeared to be the most common cause.

**Comment by xeccgtt** [comment]
I have this version.  It is a higher version.

M:\APM\mq_promo_monitoring>git --version
git version 2.9.2.windows.1
