### ISSUE TITLE
Prometheus cant load MQ metrics using mq_prometheus

### ISSUE THREAD

**Issue by JonasWennberg** [ibm-messaging/mq-golang#61]
I have followed the guide how to build the mq_prometheus metric collector. 
When running it on a MQ 9.0.5 server it connects to the MQ QMGR but somehow it wont gather any metrics to prometheus.
Im running on RHEL 7.4, IBM MQServer 9.0.5.0.

The mq_prometheus binary is built on a CentOS 7.5.1804 with mq-golong v2.0.0 (tried both dev-branch and master) and using Go v1.9.4.

The mq_prometheus starts with this command:
./mq_prometheus  -ibmmq.queueManager PTGLA01 -ibmmq.monitoredQueues EBCDEVSEC01 -log.level debug

The output from this is looking all good, listing all gauges and ending with:

INFO[0000] IBMMQ Describe started
INFO[0000] Listening on 9157
INFO[0056] IBMMQ Collect started

However ibmmq is not available in Prometheus.
Checking targets shows:

 ibmmq (0/1 up)
Endpoint 	State 	Labels 	Last Scrape 	Error
http://localhost:9157/metrics
	down 	instance="localhost:9157" 	24.541s ago 	server returned HTTP status 500 Internal Server Error

Doing some debuging with promtool:

Output is 2 different errors:

curl -s http://localhost:9157/metrics | ./promtool check metrics
 - error while linting: text format parsing error in line 1: expected float as value, got "error"
 - http_request_duration_microseconds use base unit "seconds" instead of "microseconds"

Can you please help me out here?
I feel I have tried everything! 

Br
Jonas Wennberg

**Comment by JonasWennberg** [comment]
Hi,

There is nothing in the MQ error logs... Regarding the publications, is prometheus collector using the same as the collectd and influx collectors found in the same examples?
The reason for asking is because they are working...  (But i really want prometheus)

Br
Jonas

**Comment by JonasWennberg** [comment]
I can mention that amqsrua works fine...

**Comment by ibmmqmet** [comment]
All the collectors use the same functions in the mqmetric package to subscribe and receive publications.

**Comment by JonasWennberg** [comment]
I have recompiled with the #63 fix but still the same issue.

**Comment by ibmmqmet** [comment]
Closing out inactive issues
