### ISSUE TITLE
When will it be compatible with 7.5?

### ISSUE THREAD

**Issue by robert871126** [ibm-messaging/mq-golang#65]
Please include the following information in your ticket.

- Version information for MQ, mq-golang, Go compiler
- A small code sample that demonstrates the issue.

**Comment by ibmmqmet** [comment]
The code will connect as a client to any version of MQ. Though the monitoring features are only available with the V9 queue manager. 

But as V7.5 is already out of service (April 2018), I've no plans to add the changes needed to compile the wrapper against that obsolete level of MQ library.
