### ISSUE TITLE
v3 with go.mod

### ISSUE THREAD

**Issue by tgulacsi** [ibm-messaging/mq-golang#69]
Please merge (I cannot create a PR for that specific commit, don't know why)
https://github.com/ibm-messaging/mq-golang/commit/e251c2c856dbb4ca3483567df3cc4b3197cfee59

Just adds the 'go modules' required /v3 to the import paths (see https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher).

**Comment by ibmmqmet** [comment]
#121 also mentions go modules. Since those are now more stable than a year ago, I'll keep that one on the books for investigation but close this.
