### ISSUE TITLE
Wrong structure lengths in cmqc_linux.go

### ISSUE THREAD

**Issue by yurist** [ibm-messaging/mq-golang#7]
All structure lengths are generated as 8, for example:

	MQTM_CURRENT_LENGTH int32 = 8

instead of 684, cmqc.h:

    #define MQTM_CURRENT_LENGTH            684

See
https://github.com/ibm-messaging/mq-golang/blob/master/ibmmq/cmqc_linux.go#L4223

**Comment by ibmmqmet** [comment]
Thanks for the report. I can see how that happened when generating the header (the awk was too simplistic). 

One problem is that there are actually two values for many of those lengths, depending on whether it's a 32 or 64-bit C interface. You'd see them in the product's cmqstrc.h marked as 4 or 8 byte values, or in an ifdef in cmqc.h.

For Go programs I doubt these values are useful at all anyway, so I may just remove them. An MQTM defined as a Go structure would have a meaningless length - it's not like you would malloc the space for one, and anything really manipulating that structure needing the lengths would be in a C wrapper, able to refer directly to the C headers.

**Comment by yurist** [comment]
Thanks for the response. I'm not sure about other MQ structs, but the way I stumbled over it was me trying to validate trigger messages coming off initiation queue. Maybe it's me being over-defensive, but I wanted to check the datalength after MQGET to make sure I can safely move the C fields over to Go struct (everything in Go, no need for additional C wrappers.) Ended up coding the constant for the time being. Not sure how critical this is for everyone else. The current Go MQI implementation is definitely usable if rough around the edges, I guess you will invest in polishing based on the extent it's used in the wild.

Regarding 32 vs 64, my feeling is you will have to split the packages sooner or later anyway. The 32/64 issue may be quite moot for most, but for instance today you are hardwired for server bindings only, and I can't think of a way of making client bindings work other than having a separate package (mqic.go for example.)

Thanks for Go support, don't take my remarks as harsh - quite the opposite, as I say it's definitely useful.
