### ISSUE TITLE
Install on Windows 10 fails

### ISSUE THREAD

**Issue by hmpub** [ibm-messaging/mq-golang#71]
Please include the following information in your ticket.

- Version information for MQ, mq-golang, Go compiler
mq-qolang: fresh clone (minutes before install attempt)
MQ client: 9.1.0.1
GO: go version go1.11.2 windows/amd64
- A small code sample that demonstrates the issue.
D:\gomq>go install ./src/github.com/ibm-messaging/mq-golang/ibmmq
# runtime/cgo
gcc_libinit_windows.c: In function 'x_cgo_sys_thread_create':
gcc_libinit_windows.c:56:12: error: implicit declaration of function '_beginthread'; did you mean 'OpenThread'? [-Werror=implicit-function-declaration]
  thandle = _beginthread(func, 0, arg);
            ^~~~~~~~~~~~
            OpenThread
cc1: all warnings being treated as errors

GCC:
D:\gomq>gcc --version
gcc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Installed via cygwin

OS:
Win 10 Pro (1803) VM on azure

**Comment by ibmmqmet** [comment]
Try using the mingw variant of the compiler. The basic gcc tries to create a cygwin-aware program, dependent on cygwin libraries, where the mingw will create a more Windows-aware standalone program.

From the README here: `set CC=x86_64-w64-mingw32-gcc.exe`

**Comment by hmpub** [comment]
First of all, sorry for the late reply. I have been kind of tied up at work and my mail provider decided to qualify the notification mail as spam :-(

I followed your recommendation and uses the mingw variant. The "go install" went without complaint and the ibmmq.a file is now present.

Thanks a lot for the help!
