### ISSUE TITLE
Monitoring HA

### ISSUE THREAD

**Issue by salapat11** [ibm-messaging/mq-golang#73]
MQ - v9.0.0.2
mq-golang - v3.0.1
Go - 1.11

Is there any impact on the monitor program if HA (Active/Active) is enabled on Prometheus?

**Comment by ibmmqmet** [comment]
What is the Prometheus architecture in this setup? The monitor program will respond to whoever calls its http interface with the current statistics, which effectively resets the next interval to zero. So if two Prometheus instances are calling the monitor independently, then half the data will go to one, half the data will go to the other. And then it would depend on whether there's a single shared database or not.

**Comment by salapat11** [comment]
Prometheus architecture will be Active/Active.  To tolerate Prometheus server outages, Active/Active is the desired approach.  Yes, it should be a shared database between the two instances.  
We are also looking into implementing Thanos components for long term storage.  The requirement is to search for 1 year old statistics data.
