### ISSUE TITLE
Metrics from z/OS

### ISSUE THREAD

**Issue by salapat11** [ibm-messaging/mq-golang#78]
Does the current version of go-lang libraries support pulling metrics from z/OS v8?  We are looking to leverage the QSTATUS and CHSTATUS commands.

**Comment by ibmmqmet** [comment]
Don't know of any reason why it wouldn't work.

**Comment by salapat11** [comment]
Thanks Mark.  How can be Golang installed on z/os?

**Comment by ibmmqmet** [comment]
You don't. You connect to the qmgr as a client from somewhere else.
