### ISSUE TITLE
Metrics are truncated

### ISSUE THREAD

**Issue by salapat11** [ibm-messaging/mq-golang#80]
MQ - v9.0.0.2

We have a queue manager with 282 queues.  The MODEL queue has a MAXDEPTH of 60000.  Some metrics are not being exposed (ibm_queue_depth).  Should the model queue depth be increased to a higher value?  There is a warning in the log that the depth of the model queue is low.  The polling is every 30s.

**Comment by salapat11** [comment]
It was mentioned in the calculation that "Current published resource topics are approx 95 for qmgr and 35 per queue".  Is this the number of messages put to the temp queue for each poll?
The subscriptions are 13 per qmgr and 4 per each queue.

**Comment by ibmmqmet** [comment]
For z/OS you shouldn't need to increase the queue depth on the model queue. I'll probably remove that warning for the platform in the next update. You wrote `ibm_queue_depth` as a metric - it's `ibmmq_queue_depth`.

**Comment by salapat11** [comment]
This is not for z/OS.  Yes, queue depth and some other metrics are not being exposed.

**Comment by salapat11** [comment]
Still facing this issue?  MAXHANDS on queue manager is set to 256.  Is this value limiting the subscriptions to go beyond 256?

**Comment by salapat11** [comment]
Works perfectly for monitoring up to 55-60 queues.  Beyond that some metrics are not generated.

**Comment by ibmmqmet** [comment]
Could well be MAXHANDS then. It looks like the code may not be checking for errors in all cases during the subscription processing. I'll see if I can create/test a fix before pushing the next update.

**Comment by salapat11** [comment]
Thanks Mark.  What are the consequences if MAXHANDS is increased to a higher value?  The work around is to split monitoring into multiple processes with each process monitoring ~60 queues.

**Comment by ibmmqmet** [comment]
MAXHANDS doesn't have any real effect other than to stop runaway apps from continually opening queues. Having a large number doesn't, in itself, use additional resources on the qmgr

**Comment by salapat11** [comment]
Thanks again!

**Comment by salapat11** [comment]
Increasing the MAXHANDS parameter solved the issue.  Thanks.
