### ISSUE TITLE
Can you give an example of how to use the connx method?

### ISSUE THREAD

**Issue by crazyvv** [ibm-messaging/mq-golang#9]
I used mqitest.go code, and made some changes
```
	gocno := ibmmq.NewMQCNO()
	gocno.Options = 0x00000080
	gocno.CCDTUrl = "mq.test.com(1486)"
        qMgr, mqreturn, err := ibmmq.Connx(qMgrName, gocno)
```
         or  ` gocno.CCDTUrl = "file:///xxx/ccdt.TAB"`
go run mqitest.go
The results are as follows

> MQCONN: MQCC = MQCC_FAILED [2] MQRC = MQRC_Q_MGR_NAME_ERROR [2058]

I want to connect to a remote queue manager
Can you give an example of how to use the  Connx method?

**Comment by ibmmqmet** [comment]
The CCDTURL field does need to be pointing to the client channel table (file), not being set to what looks like a CONNAME, or the MQSERVER environment variable. Assuming that the CCDT does have the correct contents for the qmgr you're connecting to, then you are probably missing the CNO option to use the client connection.

And there is an example of using that CNO option in the mqmetric/mqif.go file, where it's used to set the connection mode (client/local).

**Comment by crazyvv** [comment]
Sorry, I do not understand how webshpere mq works.
And not good at English, very sorry
I look at your example, which seems to be on how to connect the local queue.

My situation is as follows:
> Client server (192.168.1.1)
> Env: golang / python

> MQ server (192.168.1.2)
> Env: ibm websphere mq
> Port: 1486
> Conn_name: 192.168.1.2 (1486)
> Chanel: chanel_name
> Qmgrname: qmgr_name

I know how to use pymqi python implementation. Very simple
```
Qmgr = pymqi.connect ("qmgr_name", "chanel_name", "192.168.1.2 (1486)")
Queue = pymqi.Queue (qmgr, queue_name)
Message = queue.get ()
```
But I hope to achieve it through golang, how should I do?
Can you give me some simple code?

**Comment by ibmmqmet** [comment]
There is currently no way in the Go interface to programatically set the connection information for a remote queue manager. I may add that capability (via the MQCD structure) at some point, but not immediately.

Instead, you can 

- set the [MQSERVER](http://www.ibm.com/support/knowledgecenter/SSFKSJ_9.0.0/com.ibm.mq.con.doc/q017020_.htm) environment variable, Do something like 'export MQSERVER="MY.SVRCONN/TCP/192.168.0.1(1414)"' before running the program.

- use a Client Channel Definition Table [CCDT](http://www.ibm.com/support/knowledgecenter/SSFKSJ_9.0.0/com.ibm.mq.con.doc/q016730_.htm). 

The CCDT can be accessed by environment variables, with various defaults depending on platform as documented [here](http://www.ibm.com/support/knowledgecenter/SSFKSJ_9.0.0/com.ibm.mq.con.doc/q016920_.htm) or via the CCDTURL property.

Depending on what else you have installed, you may also need to set the MQCNO_CLIENT_BINDING option on the cno, as shown in mqif.go. Apart from setting that option, there's no API difference for local or remote connections; the definition of where to connect to is all handled externally via the environment or CCDT definitions.

Part of the  intention of this Go interface was to present a reasonably-complete MQI model, following the same approach as the C API. Even though not everything has been implemented yet, the principle still holds. 

So "simplified" functions such as the python interface which does not allow access to the full services of the API is not something I want to do here. Every time I've seen "simplified" APIs, there's always one more function that someone wants to use, leading back to more complexities that could have been avoided by doing the whole thing properly in the first place.

And to repeat, the programmatic access to the channel and connection information is certainly possible to add in future, using essentially the same approach as the C API, it's not there right now. It's more complex than just having one or two new parameters; as soon as you get into client channels, then all the TLS parameters are likely to be needed as well - which complicates application code, and abstracting it into the CCDT is a better starting point.

**Comment by ibmmqmet** [comment]
I've just pushed a new set of code to the repo including support for the MQCD structure to allow programmatic access for clients. There's also a new sample, clientconn, that shows how to use it.

**Comment by crazyvv** [comment]
Thank you very much, I have been tested according to what you said before.
Your new code and examples, I have tested, and very helpful to me.
Your new code will also bring convenience to others.
Thank you for your efforts
