### ISSUE TITLE
Cannot statically link the mqitest sample

### ISSUE THREAD

**Issue by wcn00** [ibm-messaging/mq-golang#92]
Using go version go1.11.5
using ubuntu 18 on Intel x86-64
using the mq9.1.01 installation

I need to link mq-golang (and maybe mq-golang-jms20) apps statically so that they can be distributed without dependencies.  I have set environment variables:
CGO_LDFLAGS=-L/opt/mqm/lib64  -lmqm_r -Wl,-rpath,/opt/mqm/lib64
CGO_LDFLAGS_ALLOW=-Wl,-rpath.*
CGO_CFLAGS=-I/opt/mqm/inc

I've tried many build commands but they all give the same error:

wcn00@gandalf:~/go/src/github.com/ibm-messaging/mq-golang$ go build  -ldflags '-extldflags -static '  -o ./bin/mqitest samples/mqitest/*.go
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lmqm_r
/usr/bin/ld: cannot find -lmqm_r
/usr/bin/ld: cannot find -lmqm_r
collect2: error: ld returned 1 exit status

I've set LD _LIBRARY_PATH to /opt/mqm/lib64, and I'v even added it to my ldconfig.  No help.

p.s.  I definatly can link one of the C samples on this system.  And I can dynamically link my go application.  

Any ideas?

**Comment by ibmmqmet** [comment]
The MQ client libraries (libmqm et al.) are only available in .so (shared) form. There's no .a (archive) version. I don't know any way of converting .so to ,a format for static linking.

MQ's [Redistributable Client](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.ins.doc/q122882_.htm) package is intended for inclusion in application packages.

**Comment by wcn00** [comment]
I agree that MQ is not distributed with static libs.  If the lawyers will agree to ship the redistributable client...that may solve my problem.
wcn
