### ISSUE TITLE
 Descriptions to metrics, inactivity queue monitoring, MQ on AIX

### ISSUE THREAD

**Issue by wirowka** [ibm-messaging/mq-golang#96]
hi All
I have 3 generic questions:
- is there any documentation to the metrics exposed by the mq-golang (Prometheus exporter in particular)
- we need to implement message feed monitoring (detect that local queue X has not got any message in the last 5 min), which metric could be used to implement it
- we have couple of MQ installation on AIX , how we could use this tool monitor MQ in AIX machines (is it at all possible ? or maybe it is possible to run the exporter from remote Linux machine ? Our AIX machines are pretty old unfortunately ...)

Thanks in advance for help
Best Regads
Lukasz

**Comment by ibmmqmet** [comment]
There's not a lot of documentation on the specific metrics provided by the qmgr, as they are subject to change over time. The best way to explore what is available is to [run the amqsrua](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.mon.doc/mo00013_.htm) program and play with the interactive options.

The qstatus "oldest message" may help with looking at activity. There's nothing else currently available in the public repository for looking at the status, but I do have a local prototype that uses the LastPut/LastGet fields available from the qmgr's DISPLAY QSTATUS output. That'll probably appear in a release soon.

You can connect as a client to AIX qmgrs from a remote Linux system - provided the AIX qmgrs are running at least MQ V9.0

**Comment by wirowka** [comment]
Great, thank you for the info! We will play with the current version and eagerly waiting for the new one!
This is great stuff, thanks for it!

**Comment by wirowka** [comment]
answers given, thank you!

**Comment by ibmmqmet** [comment]
ibmmq_queue_time_since_get and ibmmq_queue_time_since_put metrics should now be visible in the latest version
