### ISSUE TITLE
Build 

### ISSUE THREAD

**Issue by johnllao** [ibm-messaging/mq-golang#98]
I am using IBM MQ Redist to build and package our code for deployment to UAT and production. 

The location of the MQI libraries may be different depending on the environment (e.g. /mqm/uat or /mqm/prod). 

I observed that when our application is build using the location /mqm/uat the application will always search for the MQ libraries in that location hence we cannot run the application on other environments. 

Is there a way to make it variable at runtime?  

Go version: 1.10.1
IBM MQ Redist: 9.1.1.0 
Package file: 9.1.1.0-IBM-MQC-Redist-LinuxX64.tar.gz

**Comment by ibmmqmet** [comment]
Use LD_LIBRARY_PATH or the [setmqenv](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.ref.adm.doc/q083560_.htm) command to point at different directories.
