### ISSUE TITLE
Seems to leak memory in get

### ISSUE THREAD

**Issue by wcn00** [ibm-messaging/mq-golang#99]
Using:
-ubuntu 18 linux
-mq 9.1.0.1
-current pull from github of mq-golong
I'm writing a microservice for sending and getting MQ messages.  It supports basic message properties.  The put side of the service runs forever in the same memory footprint, but the get side leaks memory.  I suspect that the leak is in the C side of the enclave (if thats the right word).  go pprof shows nothing unusual.
I've rewritten the amqprop sample to get my messages (attached) and when I run it it leaks.  
Any ideas?
[amqsprop.zip](https://github.com/ibm-messaging/mq-golang/files/3082142/amqsprop.zip)

If you need me to make the other side in a sample I can.
wcn

**Comment by wcn00** [comment]
Adding valgrind report.  Seems to indicate that there are cgo allocations not freed.
[valgrind.zip](https://github.com/ibm-messaging/mq-golang/files/3084952/valgrind.zip)

**Comment by wcn00** [comment]
Duplicated the experiment with messages without properties and observed no storage creep.

**Comment by ibmmqmet** [comment]
Looks like a buffer in InqMP is being allocated on each iteration and not freed or reused. I'm not in a good environment to fully test a fix right now so might be a few days before I can do anything about it, or to check that really is the issue.

**Comment by wcn00** [comment]
I'm in a good spot for that.  I'll test the idea, by allocating the 
properties header, and then not using it before freeing it. If you're 
idea pans out I'll test a fix.

wcn

p.s.  Thanks for responding

**Comment by wcn00** [comment]
This diff seems to resolve the issue. Thanks again for the pointer.  

diff --git a/ibmmq/mqi.go b/ibmmq/mqi.go
index ba3f54f..f90cc67 100644
--- a/ibmmq/mqi.go
+++ b/ibmmq/mqi.go
@@ -1198,12 +1198,14 @@ func (handle *MQMessageHandle) InqMP(goimpo *MQIMPO, gopd *MQPD, name string) (s
                mqName.VSPtr = (C.MQPTR)(C.malloc(namebufsize))
                mqName.VSBufSize = namebufsize
        }
+       defer C.free(unsafe.Pointer(mqName.VSPtr))
 
        copyIMPOtoC(&mqimpo, goimpo)
        copyPDtoC(&mqpd, gopd)
 
        propertyPtr = C.PMQVOID(C.malloc(propbufsize))
        bufferLength := C.MQLONG(namebufsize)
+       defer C.free(unsafe.Pointer(propertyPtr))
 
        C.MQINQMP(handle.qMgr.hConn,
                handle.hMsg,
@@ -1217,10 +1219,6 @@ func (handle *MQMessageHandle) InqMP(goimpo *MQIMPO, gopd *MQPD, name string) (s
                &mqcc,
                &mqrc)
 
-       if len(name) > 0 {
-               C.free(unsafe.Pointer(mqName.VSPtr))
-       }
-
        mqreturn := MQReturn{MQCC: int32(mqcc),
                MQRC: int32(mqrc),
                verb: "MQINQMP",

**Comment by ibmmqmet** [comment]
V4.0.5 includes a fix for this

**Comment by ibmmqmet** [comment]
closing as delivered
